
@startuml 
partition "Inclusive OR Job 1" {
  group "Inclusive OR Sequence 1"
      #green:IOJ1A;
      split
      :IOJ1B;
      split again
      :IOJ1C;
      :IOJ1D;
      end split
      :IOJ1E;
      #red:IOJ1F;
  end group
}
@enduml
