
@startuml 
partition "Multi Audit Event Data on An Event Job 1" {
  group "Multi AE Data Sequence 1"
      #green:MAEDJ1A;
      :MAEDJ1B,BCNT,user=MAEDJ1G,name=MAEDJ1BC1,LCNT,user=MAEDJ1D,name=MAEDJ1LC1;
      :MAEDJ1C;
      repeat
        :MAEDJ1D;
        :MAEDJ1E;
      repeat while
      :MAEDJ1F;
      :MAEDJ1G;
      :MAEDJ1H;
      #red:MAEDJ1I;
  end group
}
@enduml
