version: "3.9"
name: munin

volumes:
  ConanServer:
  ConanCache:


services:

  conan-server:
    image: levistarrett/conan-server
    restart: unless-stopped
    ports:
      - 9300:9300
    volumes:
      - type: volume
        source: ConanServer
        target: /conan-data

  populate:
    image: levistarrett/masl-populate
    depends_on:
      conan-server:
        condition: service_healthy

  bash:
    image: levistarrett/masl-dev
    stdin_open: true
    tty: true
    volumes:
      - type: volume
        source: ConanCache
        target: /conan-cache
    ports:
      - "20000:20000"
      - "30000:30000"
      - "40000:40000"
    environment:
      - OOA_PORT=0

  test:
    image: levistarrett/masl-dev
    stdin_open: true
    tty: true
    volumes:
      - type: volume
        source: ConanCache
        target: /conan-cache
    ports:
      - "20000:20000"
      - "30000:30000"
      - "40000:40000"
    environment:
      - OOA_PORT=0
    command: bash -c "source /work/build/Release/generators/conanrun.sh && source /work/test.env && ${TEST_CMD:-exit}"

  build:
    image: levistarrett/masl-dev
    depends_on:
      conan-server:
        condition: service_healthy
    volumes:
      - type: volume
        source: ConanCache
        target: /conan-cache
    command: bash -c "conan build --build=missing --options test=${INCLUDE_TEST:-False} . && conan export-pkg ."
