version: "3.9"
name: munin

volumes:
  ConanCache:

services:
  bash:
    image: levistarrett/masl-dev:${MASL_VERSION:-latest}
    stdin_open: true
    tty: true
    volumes:
      - type: volume
        source: ConanCache
        target: /conan-cache
    ports:
      - "20000:20000"
      - "30000:30000"
      - "40000:40000"
    environment:
      - OOA_PORT=0

  test:
    image: levistarrett/masl-dev:${MASL_VERSION:-latest}
    stdin_open: true
    tty: true
    volumes:
      - type: volume
        source: ConanCache
        target: /conan-cache
    ports:
      - "20000:20000"
      - "30000:30000"
      - "40000:40000"
    environment:
      - OOA_PORT=0
    command: bash -c "source /work/build/Release/generators/conanrun.sh && export LD_LIBRARY_PATH=$${LD_LIBRARY_PATH}:/work/build/Release/lib && source /work/test.env && ${TEST_CMD:-exit}"

  build:
    image: levistarrett/masl-dev:${MASL_VERSION:-latest}
    volumes:
      - type: volume
        source: ConanCache
        target: /conan-cache
    command: bash -c "conan build --build=missing --options test=${INCLUDE_TEST:-False} . && conan export-pkg ."
