name: munin

volumes:
  conan-cache:
    name: conan-cache

services:
  bash:
    image: levistarrett/masl-dev:latest
    stdin_open: true
    tty: true
    volumes:
      - type: volume
        source: conan-cache
        target: /conan-cache
    ports:
      - "20000:20000"
      - "30000:30000"
      - "40000:40000"
    environment:
      - OOA_PORT=0

  test:
    image: levistarrett/masl-dev:latest
    stdin_open: true
    tty: true
    volumes:
      - type: volume
        source: conan-cache
        target: /conan-cache
    ports:
      - "20000:20000"
      - "30000:30000"
      - "40000:40000"
    environment:
      - OOA_PORT=0
    command: bash -c "source /work/build/Release/generators/conanrun.sh && export LD_LIBRARY_PATH=$${LD_LIBRARY_PATH}:/work/build/Release/lib && source /work/test.env && ${TEST_CMD:-exit}"

  build:
    image: levistarrett/masl-dev:latest
    volumes:
      - type: volume
        source: conan-cache
        target: /conan-cache
    command: bash -c "conan build --version=$${MUNIN_VERSION} --build=missing --options test=${INCLUDE_TEST:-False} --lockfile-partial . && conan export-pkg --version=$${MUNIN_VERSION} --lockfile-partial ."

  create-lock:
    image: levistarrett/masl-dev:latest
    volumes:
      - type: volume
        source: conan-cache
        target: /conan-cache
    command: bash -c "conan lock create --version=$${MUNIN_VERSION} --lockfile='' ."

  publish:
    image: levistarrett/masl-dev:latest
    volumes:
      - type: volume
        source: conan-cache
        target: /conan-cache
    command: bash -c "conan-publish --version=$${MUNIN_VERSION}"
