@startuml
title FileRequest
box Sequence #LightBlue
participant client
participant server
client -> server: RequestFile
server -> server: PacketiseFile
loop "# of packets"
server -> server: AssemblePacket
alt
server -> client: TransferPacket
else break
server -> server: CorruptedPacketError
end alt
end loop
server -> client: TransferResultStatus
end box
@enduml
