scrape_configs:

  - job_name: 'prometheus'
    static_configs:
      - targets: ['127.0.0.1:9090']

  - job_name: cadvisor
    scrape_interval: 5s
    static_configs:
      - targets:
        - cadvisor:8080

  - job_name: deploy-aereception-1
    scrape_interval: 5s
    static_configs:
      - targets:
        - cadvisor:8080

  - job_name: deploy-aeo_svdc-1-1
    scrape_interval: 5s
    static_configs:
      - targets:
        - cadvisor:8080
        - grok_exporter:9144
