scrape_configs:

  - job_name: 'prometheus'
    static_configs:
      - targets: ['127.0.0.1:9090']

  - job_name: cadvisor
    scrape_interval: 5s
    static_configs:
      - targets:
        - cadvisor:8080

  - job_name: deploy-aesimulator
    scrape_interval: 5s
    static_configs:
      - targets:
        - cadvisor:8080

  - job_name: deploy-aereception
    scrape_interval: 5s
    static_configs:
      - targets:
        - cadvisor:8080

  - job_name: deploy-aeo_svdc-1
    scrape_interval: 5s
    static_configs:
      - targets:
        - cadvisor:8080

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node_exporter:9100']

