= HOWTO Stress Test

xtUML Project Implementation Note

== 1 Abstract

This note is a "living" HOWTO guiding engineers to run the Protocol
Verifier (PV) under stressful loads.

== 2 Introduction and Background

A regression script exists which does a small amount of coverage testing
of the Protocol Verifier.  Stress testing also uses a script to set up and
run the PV.  The stress testing utilises features of `plus2json --play`
which repeated run jobs playing out runtime audit event streams.

== 3 Requirements

=== 3.1 Guide Engineers in Protocol Verifier Testing

Information shall be provided that guides users and testers of the
Protocol Verifier to run in production configurations.

== 4 Work Required

. Document how to run the benchmarking script and general PV features.
. Document configuration variables.

== 5 Implementation Comments

N/A

== 6 Unit Test

When a random, intelligent engineer can follow these instructions and
successfully stess test the Munin PV, then unit test passes.

== 7 User Documentation

=== 7.1 Steps

. Navigate to munin/metrics.
. Run `run_benchmark.sh` for 20000 events.
  .. `run_benchmark.sh 1000 20000`
. Observe the log files.
  .. Check for failed jobs.
  .. `grep -c job_fail logs/verifier/*`

=== 7.2 References

==== 7.2.1 plus2json

* Run `plus2json -h` to get help text which briefly documents all
* features.  Pay special attention to 'rate' and 'num-events'.

==== 7.2.2 Interesting Commands

* `docker system prune`
* `docker volume prune`
* See CPU and memory usage.
  ** `docker stats --no-stream`

== 8 Document References

. [[dr-1]] https://onefact.atlassian.net/browse/MUN2-153[153 - build and test artefacts]

---

This work is licensed under the Creative Commons CC0 License

---
