@startuml(id=Part2)
title BankDeposit (part 2)
participant System
participant Auditor
System -> System : VerifyAmount
System -> System : VerifyAccountNumber
System -> Auditor : RequestFraudCheck
Auditor -> System: FraudCheckResponse
@enduml
