/'
  multi-line
  comment
'/
@startuml ( id = "empty block" )

@enduml
@startuml
partition "Job with Simple Sequence" {
  group "Straight Line Sequence"
    #red:A;
    :B;
    note right
      note message text
    end note
    :C;
  end group
}
@enduml
