@startuml
#green:A;
note right
  LoopCount Name=X Source=A,1 User=C,1
end note
repeat
  :B;
  :C;
  if (XOR) then (error)
    :CError;
    break
  else (normal)
    :D;
  end if
repeat while
  #red:E;
@enduml
