= Audit Events Arrays

xtUML Project Analysis Note

== 1 Abstract

This note provides requirements, analysis and work required to support the
reception of arrays of audit events (in JSON format) in the Protocol
Verifier.

== 2 Introduction and Background

As of the 1.4.0 (June 2024) release of Protocol Verifier, audit event
reception supports only one individual audit event JSON object per
message.  By supporting arrays of audit events the following benefits may
be realised:

* Convenience will be supplied to the upstream source of audit events in
  cases where all events for a job are in hand.
* The number of interactions with the message broker will be reduced.
  This may have a positive effect on performance depending upon the
  characteristics of a particular message broker.
* When the audit events are pre-ordered, the performance of the Protocol
  Verifier may be enhanced due to a reduction in processing and memory
  usage.

== 3 Requirements

. In the Protocol Verifier, support receiving JSON arrays of audit events
  on the 'Protocol_Verifier_Reception' topic.
. In the Protocol Verifier, support exchanging JSON arrays of audit events
  in the inter-component messaging between Job Management and Audit Event
  Ordering.
. In 'plus2json' (<<dr-2>>), support providing JSON arrays of audit events
  to the 'Protocol_Verifier_Reception' topic.
. In 'plus2json', retain support for providing individual audit
  events as discrete JSON objects to the 'Protocol_Verifier_Reception' topic.

== 4 Analysis

=== 4.1 Facts to Consider

==== 4.1.1 Scaling and Ordering Features

The Protocol Verifier has functionality and generality that may overlap
with upstream event sources.  As long as performance remains satisfactory,
this is fine.  The scalability supplied by Job Management is a strong
feature.  The out-of-order event reception capability is also a useful
feature.

==== 4.1.2 JSON Parsing

The current implementation of the Protocol Verifier parses audit event
JSON twice, once in Job Management and again in Audit Event Ordering.
This work will parse the audit event JSON only once when the event is
first received.

=== 4.2 Options to Consider

==== 4.2.1 Single Bypass

Bypass Job Management and go straight to Audit Event Ordering using a different
public service and topic.

This enhancement would be accomplished without deprecating Job Management.
The Protocol Verifier would be configured accordingly making explicit the
assumption of audit event grouping by job.

This option loses functionality.  Job Management serves as a nexus of
application health and performance statistics.  Scaling options also
are lost.

==== 4.2.2 Double Bypass

Bypass Job Management and Audit Event Ordering and go straight to Sequence
Verification using a different public service and topic.  This assumes
that all events are for the same job and that they are ordered correctly.

This enhancement would be accomplished without deprecating Job Management
and Audit Event Ordering.  The Protocol Verifier would be configured
accordingly making explicit the assumption of audit event grouping by job
and pre-ordering.

Just as 'Single Bypass', 'Double Bypass' loses functionality.  Job
Management serves as a nexus of application health and performance
statistics.  Scaling options also are lost.

==== 4.2.3 Simple Updated Reception

Using the same topic and public service, update Job Management to detect
both individual audit event JSON objects and JSON arrays of audit event
JSON objects.

`Job Management::AuditEvent` can collect these audit event JSON objects in
a list attribute of the Audit Event class (instead of the current string
attribute for a single audit event).  Support of single and multiple audit
events can be accomplished to retain capability/compatibility with
single-event reception.

Experimentation has revealed that the overhead added by the ordering of
events is small compared to the performance gained by reducing message
transaction frequency by grouping multiple events into a single message.
This implies that we can perform job grouping in Job Management even when
the list of audit events received involves multiple jobs.  In such a
scenario, Job Management can process a received message entirely and then
report the events in batches (by job) to Audit Event Ordering.

After research and experimentation, 'Simple Updated Reception' is the
option chosen.

=== 4.3 Notes

* Should Job Management Reception iterate through the received array?  [yes]
* Enhance Audit Event Ordering by supplying a new public service
  (`AcceptJsonAuditEvents`) that receives the audit event as a native array
  (`JSON::JSONArray`).
  ** In this service, Audit Event Ordering receives the array and iterates
     through it.
* Does JSON::JSON necessarily parse an entire JSON array/object when:
  ** array elements are counted?  [yes]
  ** when a field is accessed in a single array element?  [yes]

=== 4.4 Research and Benchmarking

==== 4.4.1 Concurrency

With large groups of audit events arriving at one time, the granularity of
concurrency may be affected.  Audit Event Ordering can behave in a
synchronous manner with an invocation on a domain service resulting in
direct invocation of a terminator service.  (Consider the case of a single
message containing 100 audit events.) However, Sequence Verification
processes one audit event at a time generating an event to a state machine
between each reception of an ordered audit event.  This ensures that
multiple jobs can be processed concurrently.

==== 4.4.2 Performance

Performance has been significantly improved with this work.  It seems that
the latency of interactions with the message broker is more substantial
than previously recognised.  By grouping audit events, fewer interactions
with the message broker are required.  The same amount of overall data is
being transmitted but in fewer transactions.  The observed CPU usage of
the message broker is down substantially.

It seems that a single audit event is too small of a unit of work to
efficiently transmit through the network and Protocol Verifier.

The following table documents a few samples of benchmarking results
running the Protocol Verifier in a Kafka configuration with 4 workers
being driven by `plus2json --play`.  `plus2json --play` was configured to
shuffle the events.  When events are sequenced and delivered in batches by
job, performance is even better (but only slightly).

.Performance Measurements
[options="header"]
|===
| Release              | Linux EC2 t3.xlarge | MacBook Air M2
| 1.3.0 March 2024     | 1000 events/second  | 3000 events/second
| 1.4.0 June 2024      | 700 events/second   | 2200 events/second
| 1.4.0+ December 2024 | 1200 events/second  | 4000 events/second
|===

It is noted that the performance impact of the benchmarking probe will now
be more significant and invasive.  The benchmarking probe sends multiple
messages per audit event.  Therefore, the benchmarking probe is actually
relegated to a debugging-level tool to observe audit event processing
through the Protocol Verifier.  By default, the benchmarking probe is
disabled.

=== 4.2 plus2json

`plus2json` is easily adapted to play events grouped into arrays.  The
first experiment grouped ordered audit events into arrays batched by job.
Performance improvements in the Protocol Verifier were observed
immediately.  However, a question remained whether the performance
increase was due to the audit event grouping, batching by job or ordering.
To explore this, `plus2json` was further enhanced to play out arrays of
audit events _not_ grouped by job and _not_ ordered.  This enabled the
discovery that the performance increase was primarily due to the reduction
in transactions with the messsage broker.

`plus2json` has been enhanced to support two new command line options.

`--event-array`::  Group audit events into arrays (whether shuffled or not).

`--batch-by-job`::  Group audit events into an array by job such that all
                    audit events in the message are for the same job
                    (shuffled or not).

`plus2json` retains the following command line options which are pertinent
here.

`--batch-size`:: Specify the size of the array to be used when `--event-array`
                 is active

`--shuffle`:: Shuffle audit events into a random order.

== 5 Work Required

=== 5.1 Protocol Verifier Proper

==== 5.1.1 Job Management

===== 5.1.1.1 Dictionary of JSON Arrays of Audit Events

The incoming array of audit events received on the
'Protocol_Verifier_Reception' topic may contain events from multiple
different jobs.  As a strategy to divide up the incoming array of audit
events by job, introduce a dictionary of audit event arrays (of JSON
object) keyed by jobId.  This will be populated in a loop in the
`AuditEvent.acceptAuditEvents` class-based operation.

===== 5.1.1.2 Array Reception from System Under Observation

. Step 1 (parsing to JSON and passing JSON arrays and objects internally)
  .. Change `AuditEventReception::Receiving` to use a transient called
     `rawAuditEvents`.
  .. Add `AuditEvent.acceptAuditEvents` to parse the input string.
     ... Introduce dictionary of JSON:JSONArray transient.
     ... Detect object versus array.
     ... If array, loop through audit events and populate dictionary of
         audit event arrays.
     ... If object, append the element to the dictionary.
     ... Iterate the dictionary by key (jobId) and populate the
         auditEvents array attribute of the AuditEvent class.
     ... Count the array elements and use the result to increment
         `receivedAuditEventCount`.
  .. On class AuditEvent, add attribute `auditEvents` and of type
     JSON::JSONArray (sequence of JSONElement).
  .. On class AuditEvent, change instance service `reportAuditEvent` to deal
     with input audit event of type JSON::JSONObject.
     ... As first increment, dump the JSON event to a string before sending to AEO.
  .. Test that this works within the current mode (one event at a time).
  .. TODO On class AuditEvent, remove attribute `auditEvent`.
     ... TODO Update tests to work with the list of JSON `auditEvents`.
  .. TODO Remove `AuditEvent.acceptEvent` (in lieu of `AuditEvent.acceptAuditEvents`).
  .. Test again that this works within the current mode (one event at a time).
. Step 2 (reception of an array of audit events)
  .. Supply a new terminator service, `reportAuditEvents` that handles an
     array of audit event JSON objects.
. Step 3
  .. TODO Determine a maximum number of audit events that are acceptable in a
     single audit event JSONArray.  Report a Warning if this is exceeded.
  .. Adjust counting of received audit events and events on workers.

===== 5.1.1.1 Array Transmission to Audit Event Ordering

. Step 1
  .. TODO Change `AuditEvent.reportAuditEvent` to `AuditEvent.reportAuditEvents`.
  .. See if unit tests pass on main.  It may be that these tests were not
     updated after the addition of `AuditEventReception` in the previous
     functional change.  But since File Reception still uses it, and it
     works, then keep it?  [tests fail on main]

==== 5.1.2 Audit Event Ordering

===== 5.1.2.1

. Step 1
  .. Supply a new domain service, `AcceptJsonAuditEvents` that receives an
     array of audit events as a native JSON Array.
  .. As a first increment, dump each event to a string and call
     `acceptJsonEvent` in a loop.
  .. Test this increment.
  .. Enhance `AcceptJsonAuditEvents` to do the work that `AcceptJsonEvent`
     does/did with regard to parsing out the fields.  Only do it without
     the JSON.parse step.
. Step 2
  .. TODO Bug fix <<dr-4>> :  Allow multiple event data items on an audit event.
  .. TODO Deprecate `acceptJsonEvent` and update tests.
. Step 3
  .. Adjust configured timer delays for job timeout and blocked events to
     be a bit shorter, since we can be more confident that events for each
     job will be grouped quite tightly from a temporal standpoint.

==== 5.1.3 File Reception

The regression script works.  This means that the old
`JobManagement::acceptEvent` still works.  So, the JM unit tests should be
able to continue using this mechanism.

==== 5.1.4 Sequence Verification

No work required.

=== 5.2 plus2json

. Supply an option (`event-array`) to plus2json to send JSON arrays of
  events in a single message.
. Supply an option (`batch-by-job`) to plus2json to batch events by job
  into a single message.

== 6 Acceptance Test

Run both tests below in single-event-per-message mode and in
multi-events-per-message mode.

=== 6.1 Regression

Run the `regression.sh` script and see it pass.

=== 6.2 Benchmark Stress

Run the `run_benchmark.sh` script and see it pass with adequate throughput.

== 7 Document References

. [[dr-1]] https://github.com/xtuml/munin/issues/154[154 - Support Array of Audit Events]
. [[dr-2]] https://github.com/xtuml/plus2json[plus2json GitHub repository]
. [[dr-3]] https://github.com/xtuml/plus2json/issues/154[154 - Send Array of Audit Events]
. [[dr-4]] https://github.com/xtuml/munin/issues/250[250 - Multiple event data items fails.]

---

This work is licensed under the Creative Commons CC0 License

---
