= Support Array of Audit Events

xtUML Project Analysis Note

== 1 Abstract

This note provides analysis, requirements and work required to support the
reception of arrays of audit events (in JSON format).

== 2 Introduction and Background

As of the 1.4.0 release of Protocol Verifier, audit event reception
supports only one individual audit event JSON object per message.
By supporting arrays of audit events the following benefits may be realised:

* Convenience will be supplied to the upstream source of audit events in
  cases where all events for a job are in hand.
* The number of interactions with the message broker will be reduced.
  This may have a positive effect on performance.
* When the audit events are pre-ordered, the performance of the Protocol
  Verifier may be enhanced due to a reduction in processing and memory
  usage.

== 3 Requirements

. Support receiving JSON arrays of audit events in the Protocol Verifier.
. Support sending JSON arrays of audit events in 'plus2json' <<dr-2>>.

== 4 Analysis

=== 4.1 Facts to Consider

==== 4.1.1 Scaling and Ordering Features

The Protocol Verifier may have functionality and generality that can
overlap with upstream event sources.  As long as performance remains
satisfactory, this is fine.  The scalibility supplied by Job Management
and the out-of-order event reception capability are strong features.

In configurations in which events arrive ordered and batched by job, the
functionality of Job Management and Audit Event Ordering are less
important.  However, in such configurations, the packaging of the Protocol
Verifier can be such that Job Management, Audit Event Ordering and
Sequence Verification reside in a single executable.  Such packaging
reduces the load of message passing which will more than make up for the
redundant processing of Job Management and Audit Event Ordering while
leaving the Protocol Verifier general purpose for scaling and ordering.

==== 4.1.2 JSON Parsing

The current implementation of the Protocol Verifier parses audit event
JSON twice, once in Job Management and again in Audit Event Ordering.
This work will parse the audit event JSON only once when the event is
first received.

=== 4.2 Options to Consider

==== 4.2.1 Simple Updated Reception

Using the same topic and public service, update Job Management to detect
both individual audit event JSON objects and JSON arrays of audit event
JSON objects.

Job Management::AuditEvent can collect these audit event JSON objects in
a list attribute of the Audit Event class (instead of the current string
attribute for a single audit event).  Support of single and multiple audit
events will be accomplished to retain compatibility with single-event
reception.

==== 4.2.2 Single Bypass

Bypass Job Management and go straight to Audit Event Ordering using a different
public service and topic.

This enhancement would be accomplished without deprecating Job Management.
The Protocol Verifier would be configured accordingly making explicit the
assumption of audit event grouping by job.

==== 4.2.3 Double Bypass

Bypass Job Management and Audit Event Ordering and go straight to Sequence
Verification using a different public service and topic.  This assumes
that all events are for the same job and that they are ordered correctly.

This enhancement would be accomplished without deprecating Job Management
and Audit Event Ordering.  The Protocol Verifier would be configured
accordingly making explicit the assumption of audit event grouping by job
and pre-ordering.

=== 4.3 Notes

* keeping the array in order
  ** If JM parses out the array elements, how do we make sure we send them
     to the worker in the order received?  (after linking them to the job)
* Job Management Reception rips through the array?  [yes]
* Supply a public service on Audit Event Ordering that receives the audit event as a
  native JSON object.
* Audit Event Ordering receives the array and rips through it?  [yes, in
  separate work]
* Does JSON::JSON necessarily parse an entire JSON array/object when:
  ** array elements are counted?  [yes]
  ** when a field is accessed in a single array element?  [yes]
* What do we do with the audit event counter in JM?  [increment in the
  same place (reportAuditEvent)]
* What about the other throughput and health metrics from JM?  [remain the
  same for now]

=== 4.1 Protocol Verifier Proper

=== 4.2 plus2json

== 5 Work Required

=== 5.1 Protocol Verifier Proper

==== 5.1.1 Job Management

notes:

* Today, an event gets reported when first received if worker assignment is
  successful.
  ** So, in the case that this is a single audit event, we add it, generate
     an event to it, and it reports itself. ???
  ** In the case that this is a list of audit events, we add it, generate
     an event to it, and it reports itself and iterates. ???
* If worker assignment is not successful, the event accumulates against
  the unassigned job.  When assignment can be made, all of the events are
  reported in a loop.  I don't trust this loop in a configuration where
  AEO/SVDC synchronously receive inter-domain messages.  (Consider the
  case of a single message containing 100s of audit events.)

. Step 1 (parsing to JSON and passing JSON arrays and objects internally)
  .. Change `AuditEventReception::Receiving` to use a transient called
     `rawAuditEvents`.
  .. Add `AuditEvent.acceptAuditEvents` to parse the input string.
     ... Detect object versus array.
     ... If array, populate auditEvents array attribute.
     ... Get the jobID from the first element in the array.
     ... If object, append the element to the auditEvents array attribute.
     ... Count the array elements and use the result to increment
         `receivedAuditEventCount`.
  .. On class AuditEvent, add attribute `auditEvents` and of type
     JSON::JSONArray (sequence of JSONElement).
  .. On class AuditEvent, change instance service reportAuditEvent to deal
     with input audit event of type JSON::JSONObject.
     ... As first increment, dump the JSON event to a string before sending to AEO.
  .. Test that this works within the current mode (one event at a time).
  .. TODO On class AuditEvent, remove attribute `auditEvent`.
     ... TODO Update tests to work with the list of JSON `auditEvents`.
  .. TODO Remove `AuditEvent.acceptEvent` (in lieu of `AuditEvent.acceptAuditEvents`).
  .. Test again that this works within the current mode (one event at a time).
. Step 2 (native JSON to Audit Event Ordering)
  .. Supply a new terminator service, `reportAuditEvent` that handles an
     audit event as a native JSON object.
  .. Test that this works within the current mode (one event at a time).
. Step 3 (reception of an array of audit events)
  .. Consider supplying a new terminator service, `reportAuditEvents` that
     handles an array of audit event JSON objects... or do this as the first go.
. Step 4
  .. On class AuditEvent, add state machine with two states:  `Reporting` and
     `Reported`.  Reporting  which reports an audit events (to Audit Event Ordering).
     and generates `Report` to self (un-expedited) when more exist or `Done`
     when the last event in the list is delivered downstream.

==== 5.1.2 Audit Event Ordering

. Step 1
  .. nothing
. Step 2
  .. Supply a new domain service, `acceptJsonAuditEvent` that receives an
     audit event as a native JSON object.
. Step 3
  .. Supply a new domain service, `acceptJsonAuditEvents` that receives an
     array of audit events as a native JSON Array.
. Step 4
  .. Bug fix:  Allow multiple event data items on an audit event.

==== 5.1.3 Sequence Verification


=== 5.2 plus2json

. Step 1
. Step 2
. Step 3
  .. Supply an option to plus2json to batch ordered events by job into a
     single message.

== 6 Acceptance Test

Run both tests below in single-event-per-message mode and in
multi-events-per-message mode.

=== 6.1 Regression

Run the `regression.sh` script and see it pass.

=== 6.2 Benchmark Stress

Run the `run_benchmark.sh` script and see it pass with adequate throughput.

== 7 Document References

. [[dr-1]] https://github.com/xtuml/munin/issues/154[154 - Support Array of Audit Events]
. [[dr-2]] https://github.com/xtuml/plus2json[plus2json GitHub repository]
. [[dr-3]] https://github.com/xtuml/plus2json/issues/154[154 - Send Array of Audit Events]

---

This work is licensed under the Creative Commons CC0 License

---
