= Enhance Logging with `log4cplus`

xtUML Project Analysis Note

== 1 Abstract

This note outlines enhancements to the practice of logging in the Munin
Protocol Verifier application.

== 2 Introduction and Background

Until January 2024, the MASL C++ model compiler <<dr-2>> used POCO
<<dr-3>> as the underlying logging technology.  Now MASL C++ uses
`log4cplus` <<dr-4>>.  `log4cplus` provides more functionality and is
consistent with `log4j`, which is a popular logging framework for Java.

During testing of the Protocol Verifier, it was noted that the POCO logger
was using more memory than expected.  This was the trigger to change
logging technologies.

`log4cplus` is a bit different.  It makes sense to revisit the logging
strategy employed by the Munin project in the Protocol Verifier.  This
note will outline a Way Forward.

=== 2.1 Logging Best Practices

As preparation for enhancing logging, I studied a few published "Best
Practice" guides.  We will take the opportunity in Munin to adopt/apply
some of these practices while we are changing to the `log4*` idiom of
logging.

The first Best Practice to logging is to author a mission statement for
the logging and proceed from there.  (This aligns with Shlaer-Mellor
domain modelling quite nicely.)

== 3 Requirements

. Establish a Project Munin logging mission statement to guide decision
  making.
. Enable reporting to flow from logging.
. Support logging levels:
  ** Fatal
  ** Error
  ** Warning
  ** Information
  ** Debug
  ** Trace
. Support conditional log message string arithmetic.
. Establish conventions for enabled logging.
. Support logger hierarchy.
. Establish naming conventions for logger hierarchy.
. Establish rules and guidelines for the construction of log messages.

== 4 Analysis

=== 4.1 Munin Logging Mission Statement

* Munin software shall log information critical to the verification of protocols.
  This includes detection of alarms, failures and successes.
* Munin software shall be instrumented to enable the measurement of the
  perforance of the Protocol Verifier application itself (benchmarking).
* Munin software shall be judiciously instrumented with debug statements
  adequate to isolating bugs.
* The volume of production-level logging shall not exceed the volume of
  production audit event traffic.

==== 4.1.1 Breakdown of Application Traffic

The Protocol Verifier monitors devices through telemetry.  There are two
levels of detail in this telemetry, that of a _job_ and that of an
_event_.  In general, the user is interested in the status of a job.
Events are interesting only when they are erroneous.  Summaries of events
are interesting in terms of throughput.

==== 4.1.2 Job Logging

The primary deliverable log entry is the final status of a job.  A job
completes with status _successful_, _failed_ or _alarm_.  Together with
the job type (name) and identifier, this is the key status provided by the
Protocol Verifier.

==== 4.1.3 Event Logging

A secondary 

=== 4.1 Logger Hierarchy

* The top-level logger shall be 'pv' (Protocol Verifier).
* Each domain shall have a logger.
  ** 'pv.jm':  Job Management
  ** 'pv.aeo':  Audit Event Ordering
  ** 'pv.sv':  Sequence Verification
  ** 'pv.istore':  Invariant Store
  ** 'pv.vg':  Verification Gateway
* Each domain shall define at least 2 loggers:  'job' and 'event'.
  ** 'pv.jm.job':  Job Management job logger
  ** 'pv.jm.event':  Job Management event logger
* Each domain may define lower-level loggers for specific purposes.
  ** 'pv.sv.happy':  Sequence Verification Happy module (class)
  ** 'pv.sv.unhappy':  Sequence Verification Unhappy module (class)

== 5 Work Required

== 6 Acceptance Test

== 7 Document References

. [[dr-1]] https://github.com/xtuml/munin/issues/188[188 - Enhance Logging]
. [[dr-2]] https://github.com/xtuml/masl[MASL C++ Model Compiler GitHub Repository]
. [[dr-3]] https://pocoproject.org/[POCO Project]
. [[dr-4]] https://github.com/log4cplus/log4cplus[log4cplus]

---

This work is licensed under the Creative Commons CC0 License

---
