= Hash Extra-Job Invariants

xtUML Project Implementation Note

== 1 Abstract

This note documents a change to hash extra-job invariants and discontinue
persisting the cleartext values as seen in the runtime audit event
stream.

== 2 Introduction and Background

Some invariants have a lifespan of a single job.  These intra-job
invariants come into existence early in the job and disappear when the job
is complete.  Within the scope of the Protocol Verifier, intra-job
invariants only ever occupy transient program memory.

Another form of invariant, extra-job invariants, exist across many jobs across
time and process.  Extra-job invariants are defined in a "source job" and
referenced in one or more "user jobs".  (A form of) the invariant must persist
between the source job instantiation and the user job references.  As of Spring
2024, the invariants were being persisted as-is (cleartext) as read from the
audit event stream.  This practice is potentially increasing the attack surface
of the Protocol Verifier.

Going forward, the Protocol Verifier will hash the extra-job invariant
upon receipt in the source job and persist the hash.  User jobs will hash
the audit event stream extra-job invariants and compare to the hash of
source invariant.

There will be no change to processing of intra-job invariants.

== 3 Requirements

=== 3.1 Hash Extra-Job Invariants

Upon receipt in the source job, hash the extra-job invariant.

=== 3.2 Persist Hash

After hashing, persist the hash of the extra-job invariant in the Invariant
Store.

=== 3.3 Compare Hashes

In user jobs, obtain the persisted hash of the extra-job invariant, hash
the value of runtime user extra-job invariant and compare the hashes.

== 4 Work Required

Store a hash of an invariant rather than the plaintext invariant value.

. Update SVDC domain dependencies to include the `Hash_OOA` utility domain.
. In `PersistedInvariant.createSourceExtraJobInvariant`, directly after
  the `if` statement, hash the `invariantValue` before persisting it.
. In `HappyJob_AssessingLocalExtraJobInvariants`, compare the
  `eachInForceInvariant.invariantValue` with a hash of the
  `theTransientExtraJobInvariant.invariantValue`.
. Do the same in `UnhappyJob_AssessingLocalExtraJobInvariants`.
. Do the same in `UnhappyJob_ReassessingExtraJobInvariants`.

== 5 Implementation Comments

* Chose 'SHA3_256' as the hashing algorithm.

== 6 Unit Test

. Run SVDC unit tests.
. Run regression.sh.
. Run benchmarking.

== 7 User Documentation

N/A

== 8 Code Changes

- fork/repository:  xtuml/munin
- branch:  210_hash_invariant

----
 doc/notes/210_hash_invariant_int.adoc                        | 93 +++++++++++++++++++++++++++
 .../HappyJob/InstanceStateMachine/InstanceStateMachine.masl  |  3 +-
 .../SVDCclasses/PersistedInvariant/PersistedInvariant.masl   | 13 ++--
 .../InstanceStateMachine/InstanceStateMachine.masl           |  4 +-
 models/utils/Hash.int                                        | 54 ++++++++++++++++
 5 files changed, 159 insertions(+), 8 deletions(-)
----

== 9 Document References

. [[dr-1]] https://github.com/xtuml/munin/issues/210[210 - headline]

---

This work is licensed under the Creative Commons CC0 License

---
