= Using Intra-Job Invariants in the Protocol Verifier Instrumentation

xtUML Project Analysis Note

== 1 Abstract

This note documents thoughts on use of intra-job invariants in PV Instrumentation events.

== 2 Introduction and Background

The Munin team is instrumenting the Protocol Verifier to explore
and test the various use cases of protocol verification.  Since the
Protocol Verifier (PV) is itself an observable device that implements a
protocol, the PV is being instrumented for observability and will be used
as both the observer and the device under observation.

This paper discusses the use and potential benefits of including the use of intra-job invariants within
the instrumentation events generated by the PV itself.

=== 2.1 Why would we add this feature?

Firstly, the use of __intra-job invariants__ in instrumentation events generated by the PV are potentially 
useful in the context of verifying the behaviour of the PV itself (by __PV Prime__).

Secondly, it extends the coverage of the verification mechanisms used in the instrumentation of PV.

Finally, it provides further evidence for the extent that PV "eats its own dog food" - i.e. boostrapping the PV such 
it's own behaviour can be tested and verified.

=== 2.2 Alternative mechanisms for creating intra-job invariant values

TBD - additional domain, extension of Invaraiant Store, built into VerificationGateway

=== 2.3 Delivery Point

TBD - include in September delivery or define requirement and implement in next phase.

== 3 Proposal

=== 3.1 Update ProtocolVerifier job specification

TBD - add invariant source on first happy event from SVDC and invariant usage on 

=== 3.2 Extend Invariant Store to provide additiona services for Intra Job Invariants

TBD - Add mechanism for generating and using invariant values for use in PV instrumentation events.
- generate intra-job invariant (sets the invariant value)
- getNamedIntraJobInvariant (gets the invariant value)

=== 3.3 Extend terminator services in AEO and SVDC and possibly also AER

TBD - services need to support event passing to gateway with event data that includes an
intrajob invariant


=== 3.4 Expand and Refine Documentation

Continue to upgrade and maintain usage notes with an eye toward long-term
support of the Protocol Verifier and its user base.



== 5 Work Required

== 6 Acceptance Test

== 7 Document References

. [[dr-1]] https://onefact.atlassian.net/browse/MUN2-122[MUN2-122]

---

This work is licensed under the Creative Commons CC0 License

---
