= PV Prime Analysis

xtUML Project Analysis Note

== 1 Abstract

This note documents high-level requirements for a prototype PV of PV.

== 2 Introduction and Background

It has been noted that the Protocol Verifier obeys a specific protocol
particular to itself.  Adherence to a prescribed sequence of processes
must hold for the correct functioning of the Protocol Verifier.  It has
been proposed that this sequence could be captured and documented in a
PLUS job definition (expressed in PlantUML), and that the Protocol Verifier
could be observed by another Protocol Verifier.

The Munin team is instrumenting the Protocol Verifier for observation for
a variety of reasons including:

* gaining an understanding of the user experience of instrumenting an
  application for observation.
* gaining experience with the usage of the Protocol Verifier.
* learning to choose audit points in an application to achieve
  satisfactory protocol verification.

== 3 Requirements

=== 3.1 PV PLUS Job Definition

Produce a PLUS Job Definition that captures at an appropriate level of
abstraction the key points of observation of protocol verification
process.

=== 3.2 Application Instrumentation

Instrument the Protocol Verifier application for interfacing with the
Protocol Verifier.  Document the strategy and the mechanics.

=== 3.3 HOWTO Documentation

As by-product of this development, publish Protocol Verifier usage
guidance which is oriented toward the instrumentation of any application
for observability.

== 4 Analysis

=== 4.1 Alternative Approaches

There are a few alternatives to realising the above requirements.  Some of
these were discussed in a team meeting and are captured here.

==== 4.1.1 Logger-Based Instrumentation

A simple and expedient solution would be to use our logger and scrape the
log files post processing.  This lacks some real-time nature but
sufficiently demonstrates the protocol verification capability.  The
logger could be configured with a channel/stream specific to the PV.
This logger channel is best indirected behind a terminator.  The
terminator service can call the logger (for now).  Such indirection will
allow us to easily move to different reporting mechanism/implemetation
(such as a Kafka topic) in the future.

This is the direction we will head first.

==== 4.1.2 Open Telemetry Endpoint

We could log using Open Telemetry / Open Metrics.  This would result in us
learning a bit more about OT in concert with our work on PV instrumentation.

==== 4.1.3 Separate Protocol Verification Reporting Domain

We could build a separate PV connection domain.

==== 4.1.4 Architecture (Model Compiler) Based Instrumentation

We could do something more architecturally oriented like marking certain
states or events/transitions.  The model compiler could then generate
runtime audit event instance production.

== 5 Work Required

=== 5.1 Define a Reporting Channel

Define a new terminator service to be invoked from the application to
deliver audit event instance information including jobID, eventType,
eventID, previousEventIds, etc.

NOTE:  This information is PVprime information not information from the
       application data stream.  We do not want to leak application level
       information into the PVprime audit event stream.

Provide a mechanism using the existing MASL Logger to make PV events
distinguishable within the log files (such as "PV" or "PROTVER").

Call the logger from within the terminator service.

=== 5.2 Identify Key Application Events

Identify key points in the application that must be visited for
observability purposes.

=== 5.3 Construct the PLUS Job Definition

Construct a PLUS job definition prescribing the required sequenced audit
events and unsequenced unhappy path events through the application.  Mark
any necessary critical audit events.

==== 5.3.1 Testing the PLUS Job Definition

Not really part of this work, but useful anyway...  Test the Protocol
Verifier using this new job definition.  Consider adding it to the
regression suite as a test case (not PV of PV related but simply an
example of a legal job definition).

=== 5.4 Instrument the Application

==== 5.4.1 Job and Event Identification and Linkage

Define a strategy to identify job and event instances.  Fabricate ID
factories as needed.

Define a strategy to propagate previous event identifiers forward to
subsequent audit events.

Document challenges and struggles along the way, as this seems to be one
of the bigger challenges to users of the Protocol Verifier.

==== 5.4.2 Source Code Changes

Instrument the application source to log sequenced and unsequenced audit
events to the new PV Logger channel.  Supply the needed information to
populate a legal runtime audit event instance.

=== 5.5 Log Harvesting

Define requirements for extracting information from the log files and
producing schema-compliant audit event instance data.

Build (or delegate) a log scraper to convert the log files to runtime
audit event instance JSON files.

=== 5.6 Test

Stitch it all together and run it.  Run the regression tests.  Scrape the
resulting PV logs.  Feed the results into PV'.  See expected results.

=== 5.7 Publish HOWTO

Author a HOWTO harvesting experience to be enjoyed by those who follow.

== 6 Acceptance Test

. Run `regression.sh`.
. Collect and scrape PV logs into PV' audit event instance files.
. Run PV' feeding it the PV of PV audit event instances.
. Observe correct behaviour.

== 7 Document References

. [[dr-1]] https://onefact.atlassian.net/browse/MUN2-116[PVprime Analysis JIRA issue]

---

This work is licensed under the Creative Commons CC0 License

---
