version: "3.9"
services:
  istore_test:
    image: "ghcr.io/xtuml/istore:test"
    build:
      context: .
      target: install-test
      args:
        EXTRA_MASL_ARGS: "-skiptranslator Sqlite"
    ports:
      - "20000:20000"
      - "30000:30000"
      - "40000:40000"
    volumes:
      - "./test_results:/root/test_results"
      - "./test-files:/root/test-files"
      - "./InvariantStore:/root/InvariantStore"
    entrypoint: ["/usr/bin/timeout", "30000s", "IStore_transient_standalone"]
    command: " -postinit schedule/test-2.sch -util Inspector -inspector-port 0"
  istore_test-2:
    image: "ghcr.io/xtuml/istore:test"
    build:
      context: .
      target: install-test
      args:
        EXTRA_MASL_ARGS: "-skiptranslator Sqlite"
    volumes:
      - "./test_results:/root/test_results"
      - "./InvariantStore:/root/InvariantStore"
    entrypoint: ["/usr/bin/timeout", "30000s", "IStore_transient_standalone"]
    command: " -postinit schedule/test-2.sch -util Inspector -inspector-port 0"
