version: '3.9'
volumes:
  ConanCache:
    name: munin_ConanCache
    external: true

services:

  aer_proc:
    image: levistarrett/masl-dev
    deploy:
      replicas: 1
    depends_on:
      kafka:
        condition: service_healthy
    volumes:
      - type: volume
        source: ConanCache
        target: /conan-cache
      - "../models/PV_PROC/build:/work/build"
      - "../models/PV_PROC/schedule:/root/schedule"
      - "./config:/root/config"
      - "./logs/reception:/var/log/reception"
      - "./reception-processed:/root/processed"
    working_dir: /root
    command: bash -c "source /work/build/Release/generators/conanrun.sh && /work/build/Release/bin/AER_PROC_transient -configFile pv-config.json -log-config config/log-config-pv-proc.xml -util Kafka -kafka-broker-list kafka:9093 -kafka-group-id reception_group_1 -util MetaData"

  aeo_svdc_proc_1:
    image: levistarrett/masl-dev
    depends_on:
      kafka:
        condition: service_healthy
    volumes:
      - type: volume
        source: ConanCache
        target: /conan-cache
      - "../models/PV_PROC/build:/work/build"
      - "../models/PV_PROC/schedule:/root/schedule"
      - "./config:/root/config"
      - "./logs/verifier:/var/log/verifier"
      - "./InvariantStore:/root/InvariantStore"
      - "./JobIdStore:/root/JobIdStore"
    working_dir: /root
    command: bash -c "source /work/build/Release/generators/conanrun.sh && /work/build/Release/bin/AEO_SVDC_PROC_transient -configFile pv-config.json -log-config config/log-config-pv-proc.xml -log-param instance_index=1 -startJobGroup 00 -endJobGroup FF -util Kafka -kafka-broker-list kafka:9093 -util MetaData"

  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    ports:
     - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    ports:
     - "9092:9092"
    expose:
     - "9093"
    healthcheck:
      test: /opt/kafka/bin/kafka-topics.sh --bootstrap-server kafka:9093 --topic default.AEOrdering_service0,default.AEReception_service0 --describe
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "default.AEOrdering_service0:8:1,default.AEReception_service0:8:1"
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
