services:
  pv_proc:
    image: levistarrett/masl-dev:latest
    volumes:
      - type: volume
        source: conan-cache
        target: /conan-cache
      - "../models/PV_PROC/build:/work/build"
      - "../models/PV_PROC/schedule:/root/schedule"
      - "./config:/root/config"
      - "./InvariantStore:/root/InvariantStore"
    ulimits:
      sigpending: -1
    working_dir: /root
    logging:
      driver: local
    entrypoint: /root/config/entrypoint.sh
    command: PV_PROC_transient -log-config config/log-pv-activemq.properties -configFile ${CONFIG_FILE:-pv-config.json} -util ActiveMQ -activemq-hostname host.docker.internal -util MetaData

volumes:
  conan-cache:
    name: conan-cache
    external: true
