version: "3.9"
services:
  pv_proc:
    image: levistarrett/masl-dev:${MASL_VERSION:-latest}
    volumes:
      - type: volume
        source: ConanCache
        target: /conan-cache
      - "../models/PV_PROC/build:/work/build"
      - "./config:/root/config"
      - "./logs/reception:/var/log/reception"
      - "./logs/verifier:/var/log/verifier"
      - "./reception-incoming:/root/incoming"
      - "./reception-processed:/root/processed"
      - "./InvariantStore:/root/InvariantStore"
      - "./JobIdStore:/root/JobIdStore"
    ports:
      - "20000:20000"
      - "30000:30000"
      - "40000:40000"
    environment:
      - OOA_PORT=0
    ulimits:
      sigpending: -1
    working_dir: /root
    command: bash -c "source /work/build/Release/generators/conanrun.sh && export LD_LIBRARY_PATH=$${LD_LIBRARY_PATH}:/work/build/Release/lib && /work/build/Release/bin/PV_PROC_transient -fileStore -configFile pv-config.json -log-config config/log-config-pv-proc.properties -util Inspector"

volumes:
  ConanCache:
    name: ConanCache
    external: true
