volumes:
  conan-cache:
    name: conan-cache
    external: true

services:
  jm_proc:
    image: levistarrett/masl-dev:${MASL_VERSION:-latest}
    deploy:
      replicas: 1
    volumes:
      - type: volume
        source: conan-cache
        target: /conan-cache
      - "../models/PV_PROC/build:/work/build"
      - "../models/PV_PROC/schedule:/root/schedule"
      - "./config:/root/config"
    ulimits:
      sigpending: -1
    logging:
      driver: local
    working_dir: /root
    command: bash -c "source /work/build/linux-armv8-gcc-14/Release/generators/conanrun.sh && export LD_LIBRARY_PATH=$${LD_LIBRARY_PATH}:/work/build/linux-armv8-gcc-14/Release/lib && /work/build/linux-armv8-gcc-14/Release/bin/JM_PROC_transient -log-config config/log-pv-kafka.properties -configFile ${CONFIG_FILE:-pv-config.json} -util Kafka -kafka-broker-list kafka:9093 -kafka-group-id PVKafkaGroup -util MetaData"

  istore_proc:
    image: levistarrett/masl-dev:${MASL_VERSION:-latest}
    volumes:
      - type: volume
        source: conan-cache
        target: /conan-cache
      - "../models/PV_PROC/build:/work/build"
      - "../models/PV_PROC/schedule:/root/schedule"
      - "./config:/root/config"
      - "./InvariantStore:/root/InvariantStore"
    ulimits:
      sigpending: -1
    logging:
      driver: local
    working_dir: /root
    command: bash -c "source /work/build/linux-armv8-gcc-14/Release/generators/conanrun.sh && export LD_LIBRARY_PATH=$${LD_LIBRARY_PATH}:/work/build/linux-armv8-gcc-14/Release/lib && /work/build/linux-armv8-gcc-14/Release/bin/ISTORE_PROC_sqlite -db ./InvariantStore/InvariantStore.db -log-config config/log-pv-kafka.properties -util Kafka -kafka-broker-list kafka:9093 -kafka-offset-reset latest -util MetaData"

  aeo_svdc_proc:
    image: levistarrett/masl-dev:${MASL_VERSION:-latest}
    deploy:
      replicas: 4
    volumes:
      - type: volume
        source: conan-cache
        target: /conan-cache
      - "../models/PV_PROC/build:/work/build"
      - "../models/PV_PROC/schedule:/root/schedule"
      - "./config:/root/config"
    ulimits:
      sigpending: -1
    logging:
      driver: local
    working_dir: /root
    command: bash -c "source /work/build/linux-armv8-gcc-14/Release/generators/conanrun.sh && export LD_LIBRARY_PATH=$${LD_LIBRARY_PATH}:/work/build/linux-armv8-gcc-14/Release/lib && /work/build/linux-armv8-gcc-14/Release/bin/AEO_SVDC_PROC_transient -log-config config/log-pv-kafka.properties -configFile ${CONFIG_FILE:-pv-config.json} -util Kafka -kafka-broker-list kafka:9093 -kafka-offset-reset latest -util MetaData"
