include: # Comment out this block to run the PV without ActiveMQ
  - docker-compose.activemq.yml

services:
  jm_proc: &pv_service
    image: levistarrett/masl-dev:latest
    depends_on: # Comment out this block to run the PV without ActiveMQ
      apache-activemq:
        condition: service_healthy
    volumes:
      - conan-cache:/conan-cache
      - ../models/PV_PROC/build:/work/build
      - ./config:/root/config:ro
      - ./certs/client:/certs
    ports:
      - 20000:20000
      - 30000:30000
      - 40000:40000
    environment:
      - OOA_PORT=0
    working_dir: /root
    entrypoint: /root/config/entrypoint.sh
    command: |
      JM_PROC_transient -log-config config/log-pv-activemq.properties -configFile ${CONFIG_FILE:-pv-config.json} \
        -util MetaData -util ActiveMQ -activemq-hostname apache-activemq \
        -util Inspector
    # Uncomment to enable SSL configuration (note: must enable in docker-compose.activemq.yml as well)
    #   -ssl-ca /certs/client_ca.pem -ssl-key /certs/client.pem -ssl-password password

  istore_proc:
    <<: *pv_service
    volumes:
      - conan-cache:/conan-cache
      - ../models/PV_PROC/build:/work/build
      - ./config:/root/config:ro
      - ./certs/client:/certs
      - invariant-store:/root/InvariantStore/
    ports: []
    command: |
      ISTORE_PROC_sqlite -log-config config/log-pv-activemq.properties \
        -util MetaData -util ActiveMQ -activemq-hostname apache-activemq -db ./InvariantStore/InvariantStore.db \
    # Uncomment to enable SSL configuration (note: must enable in docker-compose.activemq.yml as well)
    #   -ssl-ca /certs/client_ca.pem -ssl-key /certs/client.pem -ssl-password password

  aeo_svdc_proc:
    <<: *pv_service
    deploy:
      replicas: 4
    ports: []
    command: |
      AEO_SVDC_PROC_transient -log-config config/log-pv-activemq.properties -configFile ${CONFIG_FILE:-pv-config.json} \
        -util MetaData -util ActiveMQ -activemq-hostname apache-activemq \
    # Uncomment to enable SSL configuration (note: must enable in docker-compose.activemq.yml as well)
    #   -ssl-ca /certs/client_ca.pem -ssl-key /certs/client.pem -ssl-password password

volumes:
  invariant-store:
  conan-cache:
    name: conan-cache
    external: true
