volumes:
  conan-cache:
    name: conan-cache
    external: true

services:
  jm_proc:
    image: levistarrett/masl-dev:latest
    deploy:
      replicas: 1
    volumes:
      - type: volume
        source: conan-cache
        target: /conan-cache
      - "../models/PV_PROC/build:/work/build"
      - "../models/PV_PROC/schedule:/root/schedule"
      - "./config:/root/config"
    ulimits:
      sigpending: -1
    logging:
      driver: local
    working_dir: /root
    entrypoint: /root/config/entrypoint.sh
    command: JM_PROC_transient -log-config config/log-pv-kafka.properties -configFile ${CONFIG_FILE:-pv-config.json} -util Kafka -kafka-broker-list kafka:9093 -kafka-group-id PVKafkaGroup -util MetaData

  istore_proc:
    image: levistarrett/masl-dev:latest
    volumes:
      - type: volume
        source: conan-cache
        target: /conan-cache
      - "../models/PV_PROC/build:/work/build"
      - "../models/PV_PROC/schedule:/root/schedule"
      - "./config:/root/config"
      - "./InvariantStore:/root/InvariantStore"
    ulimits:
      sigpending: -1
    logging:
      driver: local
    working_dir: /root
    entrypoint: /root/config/entrypoint.sh
    command: ISTORE_PROC_sqlite -db ./InvariantStore/InvariantStore.db -log-config config/log-pv-kafka.properties -util Kafka -kafka-broker-list kafka:9093 -kafka-offset-reset latest -util MetaData

  aeo_svdc_proc:
    image: levistarrett/masl-dev:latest
    deploy:
      replicas: 4
    volumes:
      - type: volume
        source: conan-cache
        target: /conan-cache
      - "../models/PV_PROC/build:/work/build"
      - "../models/PV_PROC/schedule:/root/schedule"
      - "./config:/root/config"
    ulimits:
      sigpending: -1
    logging:
      driver: local
    working_dir: /root
    entrypoint: /root/config/entrypoint.sh
    command: AEO_SVDC_PROC_transient -log-config config/log-pv-kafka.properties -configFile ${CONFIG_FILE:-pv-config.json} -util Kafka -kafka-broker-list kafka:9093 -kafka-offset-reset latest -util MetaData
