version: "3.9"
services:
  pv_proc:
    image: levistarrett/masl-dev
    volumes:
      - type: volume
        source: ConanCache
        target: /conan-cache
      - "../models/PV_PROC/build:/work/build"
      - "../models/PV_PROC/schedule:/root/schedule"
      - "./config:/root/config"
      - "./logs/reception:/var/log/reception"
      - "./logs/verifier:/var/log/verifier"
      - "./reception-incoming:/root/incoming"
      - "./reception-processed:/root/processed"
      - "./InvariantStore:/root/InvariantStore"
      - "./JobIdStore:/root/JobIdStore"
    ports:
      - "20000:20000"
      - "30000:30000"
      - "40000:40000"
    environment:
      - OOA_PORT=0
    working_dir: /root
    command: bash -c "source /work/build/Release/generators/conanrun.sh && /work/build/Release/bin/PV_PROC_transient -configPath config/ -configFile pv-config.json  -log-config config/log-config-pv-proc.xml -log-param instance_index=1 -log-level AEOrdering=trace -log-level AESequenceDC=trace -log-level IStore=trace -log-level Verifier=trace -log-level AEReception=trace -log-level FileReception=trace -log-level Reception=trace -preinit schedule/startup.sch -startJobGroup 00 -endJobGroup FF -util Inspector"

volumes:
  ConanCache:
    name: munin_ConanCache
    external: true
