version: "3.9"
services:
  aer_proc:
    image: levistarrett/masl-dev
    deploy:
      replicas: 8
    volumes:
      - type: volume
        source: ConanCache
        target: /conan-cache
      - "../models/PV_PROC/build:/work/build"
      - "../models/PV_PROC/schedule:/root/schedule"
      - "./config:/root/config"
      - "./logs/reception:/var/log/reception"
      - "./reception-processed:/root/processed"
    working_dir: /root
    command: bash -c "source /work/build/Release/generators/conanrun.sh && /work/build/Release/bin/AER_PROC_transient -configFile pv-config.json -log-config config/log-config-pv-proc.xml -util Kafka -kafka-broker-list kafka:9093 -kafka-group-id reception_group_1 -util MetaData"
  aeo_svdc_proc_1:
    image: levistarrett/masl-dev
    volumes:
      - type: volume
        source: ConanCache
        target: /conan-cache
      - "../models/PV_PROC/build:/work/build"
      - "../models/PV_PROC/schedule:/root/schedule"
      - "./config:/root/config"
      - "./logs/verifier:/var/log/verifier"
      - "./InvariantStore:/root/InvariantStore"
      - "./JobIdStore:/root/JobIdStore"
    working_dir: /root
    command: bash -c "source /work/build/Release/generators/conanrun.sh && /work/build/Release/bin/AEO_SVDC_PROC_transient -configFile pv-config.json -log-config config/log-config-pv-proc.xml -log-param instance_index=1 -startJobGroup 00 -endJobGroup 3F -util Kafka -kafka-broker-list kafka:9093 -util MetaData"
  aeo_svdc_proc_2:
    image: levistarrett/masl-dev
    volumes:
      - type: volume
        source: ConanCache
        target: /conan-cache
      - "../models/PV_PROC/build:/work/build"
      - "../models/PV_PROC/schedule:/root/schedule"
      - "./config:/root/config"
      - "./logs/verifier:/var/log/verifier"
      - "./InvariantStore:/root/InvariantStore"
      - "./JobIdStore:/root/JobIdStore"
    working_dir: /root
    command: bash -c "source /work/build/Release/generators/conanrun.sh && /work/build/Release/bin/AEO_SVDC_PROC_transient -configFile pv-config.json -log-config config/log-config-pv-proc.xml -log-param instance_index=2 -startJobGroup 40 -endJobGroup 7F -util Kafka -kafka-broker-list kafka:9093 -util MetaData"
  aeo_svdc_proc_3:
    image: levistarrett/masl-dev
    volumes:
      - type: volume
        source: ConanCache
        target: /conan-cache
      - "../models/PV_PROC/build:/work/build"
      - "../models/PV_PROC/schedule:/root/schedule"
      - "./config:/root/config"
      - "./logs/verifier:/var/log/verifier"
      - "./InvariantStore:/root/InvariantStore"
      - "./JobIdStore:/root/JobIdStore"
    working_dir: /root
    command: bash -c "source /work/build/Release/generators/conanrun.sh && /work/build/Release/bin/AEO_SVDC_PROC_transient -configFile pv-config.json -log-config config/log-config-pv-proc.xml -log-param instance_index=3 -startJobGroup 80 -endJobGroup BF -util Kafka -kafka-broker-list kafka:9093 -util MetaData"
  aeo_svdc_proc_4:
    image: levistarrett/masl-dev
    volumes:
      - type: volume
        source: ConanCache
        target: /conan-cache
      - "../models/PV_PROC/build:/work/build"
      - "../models/PV_PROC/schedule:/root/schedule"
      - "./config:/root/config"
      - "./logs/verifier:/var/log/verifier"
      - "./InvariantStore:/root/InvariantStore"
      - "./JobIdStore:/root/JobIdStore"
    working_dir: /root
    command: bash -c "source /work/build/Release/generators/conanrun.sh && /work/build/Release/bin/AEO_SVDC_PROC_transient -configFile pv-config.json -log-config config/log-config-pv-proc.xml -log-param instance_index=4 -startJobGroup C0 -endJobGroup FF -util Kafka -kafka-broker-list kafka:9093 -util MetaData"

volumes:
  ConanCache:
    name: munin_ConanCache
    external: true
