version: "3.9"
services:
  pv_proc:
    image: "ghcr.io/xtuml/protocol_verifier"
    volumes:
      - "./config:/root/config"
      - "./logs/reception:/var/log/reception"
      - "./logs/verifier:/var/log/verifier"
      - "./reception-incoming:/root/incoming"
      - "./reception-processed:/root/processed"
      - "./InvariantStore:/root/InvariantStore"
      - "./JobIdStore:/root/JobIdStore"
    command: "PV_PROC_transient -configPath config/ -configFile pv-config.json  -log-config config/log-config-pv-proc.xml -log-param instance_index=1 -log-level AEOrdering=trace -log-level AESequenceDC=trace -log-level IStore=trace -log-level Verifier=trace -log-level AEReception=trace -log-level FileReception=trace -log-level Reception=trace -preinit schedule/startup.sch -startJobGroup 00 -endJobGroup FF -util Inspector -inspector-port 0"
