version: "3.9"
services:
  aereception:
    image: "ghcr.io/xtuml/aereception"
    deploy:
      replicas: 8
    volumes:
      - "./config:/root/config"
      - "./logs/reception:/var/log/reception"
      - "./reception-incoming:/root/incoming"
      - "./verifier-incoming:/root/outgoing"
    command: "-configPath config/ -configFile reception-config.json -log-config config/log-config-reception.xml -log-level trace -preinit schedule/startup.sch -util MetaData"
  aeo_svdc-1:
    image: "ghcr.io/xtuml/aeo_svdc"
    volumes:
      - "./config:/root/config"
      - "./logs/verifier:/var/log/verifier"
      - "./verifier-incoming:/root/incoming"
      - "./verifier-processed:/root/processed"
      - "./InvariantStore:/root/InvariantStore"
      - "./JobIdStore:/root/JobIdStore"
    command: "-configPath config/ -configFile verifier-config.json -log-config config/log-config-verifier.xml -log-param instance_index=1 -log-level trace -preinit schedule/startup.sch -util MetaData -startJobGroup 00 -endJobGroup 3F"
  aeo_svdc-2:
    image: "ghcr.io/xtuml/aeo_svdc"
    volumes:
      - "./config:/root/config"
      - "./logs/verifier:/var/log/verifier"
      - "./verifier-incoming:/root/incoming"
      - "./verifier-processed:/root/processed"
      - "./InvariantStore:/root/InvariantStore"
      - "./JobIdStore:/root/JobIdStore"
    command: "-configPath config/ -configFile verifier-config.json -log-config config/log-config-verifier.xml -log-param instance_index=2 -log-level trace -preinit schedule/startup.sch -util MetaData -startJobGroup 40 -endJobGroup 7F"
  aeo_svdc-3:
    image: "ghcr.io/xtuml/aeo_svdc"
    volumes:
      - "./config:/root/config"
      - "./logs/verifier:/var/log/verifier"
      - "./verifier-incoming:/root/incoming"
      - "./verifier-processed:/root/processed"
      - "./InvariantStore:/root/InvariantStore"
      - "./JobIdStore:/root/JobIdStore"
    command: "-configPath config/ -configFile verifier-config.json -log-config config/log-config-verifier.xml -log-param instance_index=3 -log-level trace -preinit schedule/startup.sch -util MetaData -startJobGroup 80 -endJobGroup BF"
  aeo_svdc-4:
    image: "ghcr.io/xtuml/aeo_svdc"
    volumes:
      - "./config:/root/config"
      - "./logs/verifier:/var/log/verifier"
      - "./verifier-incoming:/root/incoming"
      - "./verifier-processed:/root/processed"
      - "./InvariantStore:/root/InvariantStore"
      - "./JobIdStore:/root/JobIdStore"
    command: "-configPath config/ -configFile verifier-config.json -log-config config/log-config-verifier.xml -log-param instance_index=4 -log-level trace -preinit schedule/startup.sch -util MetaData -startJobGroup C0 -endJobGroup FF"
