version: "3.9"
services:
  aereception:
    image: "ghcr.io/xtuml/aereception"
    ports:
      - "20000:20000"
      - "30000:30000"
      - "40000:40000"
    volumes:
      - "./config:/root/config"
      - "./logs/reception:/var/log/reception"
      - "./reception-incoming:/root/incoming"
      - "./verifier-incoming:/root/outgoing"
    command: "-configPath config/ -configFile reception-config.json -log-config config/log-config-reception.xml -log-param instance_index=1 -preinit schedule/startup.sch -util Inspector -inspector-port 0"
  aeo_svdc:
    image: "ghcr.io/xtuml/aeo_svdc"
    ports:
      - "20002:20002"
      - "30002:30002"
      - "40002:40002"
    volumes:
      - "./config:/root/config"
      - "./logs/verifier:/var/log/verifier"
      - "./verifier-incoming:/root/incoming"
      - "./verifier-processed:/root/processed"
      - "./InvariantStore:/root/InvariantStore"
      - "./JobIdStore:/root/JobIdStore"
    command: "-configPath config/ -configFile verifier-config.json -log-config config/log-config-verifier.xml -log-param instance_index=1 -preinit schedule/startup.sch -util Inspector -inspector-port 2 -startJobGroup 00 -endJobGroup FF"

