version: "3.9"
services:
  aer_proc:
    image: "ghcr.io/xtuml/aer_proc"
    ports:
      - "20001:20000"
      - "30001:30000"
      - "40001:40000"
    volumes:
      - "./config:/root/config"
      - "./logs/reception:/var/log/reception"
    command: "-configPath config/ -configFile reception-config.json -log-config config/log-config-reception.xml -log-level AEReception=trace -log-level Reception=trace -preinit schedule/startup.sch -util Inspector -inspector-port 0 -util Kafka -kafka-broker-list kafka:9093"
networks:
  default:
    name: deploy_default
    external: true
