include: # Comment out this block to run the PV without ActiveMQ
  - docker-compose.activemq.yml

services:
  pv_proc:
    image: levistarrett/masl-dev:latest
    depends_on: # Comment out this block to run the PV without ActiveMQ
      apache-activemq:
        condition: service_healthy
    volumes:
      - conan-cache:/conan-cache
      - ../models/PV_PROC/build:/work/build
      - ./config:/root/config:ro
    ports:
      - 20000:20000
      - 30000:30000
      - 40000:40000
    environment:
      - OOA_PORT=0
    working_dir: /root
    entrypoint: /root/config/entrypoint.sh
    command: |
      PV_PROC_transient -log-config config/log-pv-activemq.properties -configFile ${CONFIG_FILE:-pv-config.json} \
        -util ActiveMQ -activemq-hostname apache-activemq -util Inspector

volumes:
  conan-cache:
    name: conan-cache
    external: true
