include: # Comment out this block to run the PV without ActiveMQ
  - docker-compose.activemq.yml

services:
  jm_proc: &pv_service
    image: ghcr.io/xtuml/jm_proc:latest
    depends_on: # Comment out this block to run the PV without ActiveMQ
      apache-activemq:
        condition: service_healthy
    volumes:
      - ./config:/home/nonroot/config:ro
      - ./certs/client:/certs
    command: |
      -log-config config/log-pv-activemq.properties -configFile ${CONFIG_FILE:-pv-config.json} -util ActiveMQ -activemq-hostname apache-activemq
    # Uncomment to enable SSL configuration (note: must enable in docker-compose.activemq.yml as well)
    # -ssl-ca /certs/client_ca.pem -ssl-key /certs/client.pem -ssl-password password

  istore_proc:
    <<: *pv_service
    image: ghcr.io/xtuml/istore_proc:latest
    volumes:
      - ./config:/home/nonroot/config:ro
      - ./certs/client:/certs
      - invariant-store:/home/nonroot/InvariantStore/
    command: |
      -log-config config/log-pv-activemq.properties -util ActiveMQ -activemq-hostname apache-activemq -db ./InvariantStore/InvariantStore.db
    # Uncomment to enable SSL configuration (note: must enable in docker-compose.activemq.yml as well)
    # -ssl-ca /certs/client_ca.pem -ssl-key /certs/client.pem -ssl-password password

  aeo_svdc_proc:
    <<: *pv_service
    image: ghcr.io/xtuml/aeo_svdc_proc:latest
    deploy:
      replicas: 4
    command: |
      -log-config config/log-pv-activemq.properties -configFile ${CONFIG_FILE:-pv-config.json} -util ActiveMQ -activemq-hostname apache-activemq
    # Uncomment to enable SSL configuration (note: must enable in docker-compose.activemq.yml as well)
    # -ssl-ca /certs/client_ca.pem -ssl-key /certs/client.pem -ssl-password password

volumes:
  invariant-store:
