version: "3.9"
services:
  frec_proc:
    image: "ghcr.io/xtuml/frec_proc"
    volumes:
      - "./config:/root/config"
      - "./logs/reception:/var/log/reception"
      - "./reception-incoming:/root/incoming"
      - "./reception-processed:/root/processed"
    command: "-configPath config/ -configFile file-reception-config.json -log-config config/log-config-reception.xml -log-level FileReception=debug -preinit schedule/startup.sch -util Inspector -util Kafka -kafka-broker-list kafka:9093"
  aer_proc:
    image: "ghcr.io/xtuml/aer_proc"
    ports:
      - "20001:20000"
      - "30001:30000"
      - "40001:40000"
    volumes:
      - "./config:/root/config"
      - "./logs/reception:/var/log/reception"
    command: "-configPath config/ -configFile reception-config.json -log-config config/log-config-reception.xml -log-level AEReception=trace -log-level Reception=trace -preinit schedule/startup.sch -util Inspector -inspector-port 0 -util Kafka -kafka-broker-list kafka:9093"
  aeo_svdc:
    image: "ghcr.io/xtuml/aeo_svdc"
    volumes:
      - "./config:/root/config"
      - "./logs/verifier:/var/log/verifier"
      - "./InvariantStore:/root/InvariantStore"
      - "./JobIdStore:/root/JobIdStore"
    command: "-configPath config/ -configFile verifier-config.json -log-config config/log-config-verifier.xml -log-param instance_index=1 -log-level AEOrdering=trace -log-level AESequenceDC=trace -log-level IStore=trace -log-level Verifier=trace -preinit schedule/startup.sch -startJobGroup 00 -endJobGroup FF  -util Inspector -util Kafka -kafka-broker-list kafka:9093"
networks:
  default:
    name: deploy_default
    external: true
