services:
  apache-activemq:
    image: apache/activemq-classic:latest
    volumes:
      - ./config/activemq.xml:/opt/apache-activemq/conf/activemq.xml
    ports:
      # - 8161:8161 # uncomment this line to make the ActiveMQ web console available
      - 61613:61613
    healthcheck:
      test: /opt/apache-activemq/bin/activemq status | grep "ActiveMQ is running"
      interval: 1s
      start_period: 5s
      start_interval: 1s

  pv_proc:
    image: ghcr.io/xtuml/protocol_verifier:latest
    depends_on:
      apache-activemq:
        condition: service_healthy
    volumes:
      - ./config:/home/nonroot/config:ro
      - invariant-store:/home/nonroot/InvariantStore
    ulimits:
      sigpending: -1
    command: -log-config config/log-pv-activemq.properties -configFile ${CONFIG_FILE:-pv-config.json} -util ActiveMQ -activemq-hostname apache-activemq

volumes:
  invariant-store:
