@startuml

partition "Extra Job Invariant Source Job" {
group "Extra Job Invariant Source Sequence"
  :EINVSourceA;
  note right
    This job is the source of an extra job invariant 
    used in several other jobs.
    This file also contains 2 jobs.
  end note
  :EINVSourceB;
  :EINVSourceC;
  :EINVSourceB;
  :EINVSourceC;
  :EINVSourceD,EINV,name=AUTH_TOKEN_A;
  detach
end group
}

partition "Single Complex Job" {
group "Single Sequence"

  #green:SCJA,LCNT,user=SCJS,name=LC3,BCNT,user=SCJK,name=BC2;
  :SCJB,LCNT,user=SCJE(0),name=LC1,LCNT,user=SCJD(1),name=LC2,IINV,name=SCJInvA;
  :SCJC;
  if (XOR) then ("error")
    #red:SCJR;
    detach
  else ("normal")
    fork
      repeat
        :SCJD;
        :SCJE,EINV,USER,name=AUTH_TOKEN_A;
        :SCJF;
      repeat while
      :SCJG;
      repeat
        :SCJD;
        :SCJE;
        if (XOR) then ("error")
          :SCJT;
          break
        else ("normal")
          :SCJF;
        endif
      repeat while
    fork again
      :SCJK;
      :SCJL,EINV,USER,name=AUTH_TOKEN_A;
      :SCJM;
      if (XOR) then ("error")
        #red:SCJN;
        detach
      else ("normal")  
      endif    
    fork again
      :SCJP;
      #red:SCJQ;
      detach
    fork again
      :SCJC;
      repeat
        :SCJD;
        :SCJE;
      repeat while
      :SCJF,BCNT,name=BC1;
      :SCJD,EINV,USER,name=AUTH_TOKEN_A;
      #red:SCJG;
      detach
    fork again
      repeat
        :SCJS;
      repeat while
      :SCJD;
      #red:SCJE;
      detach
    end fork
    :SCJH,IINV,USER,name=SCJInvA;
    #red:SCJJ;
    detach
  endif
end group
}
@enduml