@startuml

partition "Single Complex Job" {
group "Single Sequence"

  #green:SCJAa,BCNT,user=SCJK,name=BC2;
  :SCJAb,LCNT,user=SCJS,name=LC3;
  note right
    Note the single item of audit event data per audit event
  end note
  :SCJBa,LCNT,user=SCJE(0),name=LC1;
  :SCJBb,LCNT,user=SCJD(1),name=LC2;
  :SCJBc,IINV,name=SCJInvA;
  :SCJC;
  if (XOR) then ("error")
    #red:SCJR;
    detach
  else ("normal")
    :SJCDa;
    fork
    :SJCDb;
      repeat
        :SCJD;
        :SCJE,EINV,USER,name=AUTH_TOKEN_A;
        note right
          This is a user event for the extra job invariant sourced in Phase1_E2E_1v1a.puml
        end note
        :SCJF;
      repeat while
      :SCJG;
      repeat
        :SCJD;
        :SCJE;
        if (XOR) then ("error")
          :SCJT;
          break
        else ("normal")
          :SCJF;
        endif
      repeat while
      :SJCFa;
    fork again
      :SCJK;
      :SCJL,EINV,USER,name=AUTH_TOKEN_A;
      :SCJM;
      if (XOR) then ("error")
        #red:SCJN;
        detach
      else ("normal") 
        :null; 
        note right
          This is present because an empty else clause is not yet supported
        end note
      endif
      :SJCNa;    
    fork again
      :SCJP;
      #red:SCJQ;
      detach
    fork again
      :SCJC;
      repeat
        :SCJD;
        :SCJE;
      repeat while
      :SCJF,BCNT,name=BC1;
      :SCJD,EINV,USER,name=AUTH_TOKEN_A;
      #red:SCJG;
      detach
    fork again
      repeat
        :SCJS;
      repeat while
      :SCJD;
      #red:SCJE;
      detach
    end fork
    :SCJH,IINV,USER,name=SCJInvA;
    #red:SCJJ;
    detach
  endif
end group
}
@enduml