@startuml
package "Error Events" {
("error 1")
("error 2")
("error 2")
("error 3")
("error 4")
("error 5")
("error 6")
}
@enduml

@startuml
package "Unhappy Path Events" {
("unhappy path event 1")
("unhappy path event 2")
("unhappy path event 2")
("unhappy path event 3")
("unhappy path event 4")
("unhappy path event 5")
("unhappy path event 6")
}
@enduml