@startuml
partition "Fralloc Job 3" {
  group "Fralloc Sequence 3"
    #green:FrallocStart;
    if (XOR) then (normal)
      :chmint;
      if (XOR) then (normal)
        :ehmint;
        if (XOR) then (normal)
          :frallocEval;
          if (XOR) then (normal)
            #red:frallocOK;
            detach
          else (error)
          endif
        else (error)
          :ehmintError;
        endif  
      else (error)
        :chmintError;    
      endif 
    else (error)   
    endif
    #red:frallocError;  
  end group
}  
@enduml
