@startuml
partition "File Transfer with loop Definition" {
  group "File Transfer with loop"
    #green:RequestFileL;
    :PacketiseFileL;
    repeat
      :AssemblePacketL;
      :TransferPacketL;
    repeat while (unconstrained)
    #red:TransferResultStatusL;
  end group
}  
@enduml
