/'

Tutorial - Exclusive OR Fork Topology
  
'/

@startuml 
partition "**JobDefinition** XOR Fork" {
group **SequenceDefinition** XOR Fork
      #green:A;
      :B;
  if (XOR) then (e.g. normal)
      :C;
      :E;
      :F;
      :G;
      :K;
      #red:L;
      detach
  else (e.g. error)
      #red:D;
  endif
      detach
end group
}      
@enduml