/'

Tutorial - Inclusive OR Fork Topology
  
'/

@startuml 
partition "Incl OR Fork and Merge" {
group "Incl OR Fork and Merge"
      #green:A;
      :B;
  split 
      :C;
      :E;
      :F;
  split again
      :D;
  end split
      :G;
      :K;
      #red:L;
end group
}      
@enduml
