/'

Tutorial - Simple Sequence Definition
  
'/

@startuml 
partition "Job with Simple Sequence" {
  group "Straight Line Sequence"
      #green:A;
      :B(0);
      :C;
      :B(1);
      :C(1);
      #red:D(1);
  end group
}
@enduml
