/'

Tutorial - Split Type Fork and Merge
  
'/

@startuml 
partition "Type AND Fork and Merge in separate sequences" {
  group "P"
    #green:A;
    :B;
    fork
      #red:C;
      detach
    fork again
      #red:D;
      detach
    end fork
    -[hidden]->
  end group
  group "Q"
    fork
      -[hidden]->
      #green:G;
    fork again
      -[hidden]->
      #green:J;
    end fork
    :K;
    #red:L;
    detach
  end group
}
@enduml
