/'

Tutorial - Simple Sequence Definition with Explicit Occurrences
  
'/

@startuml 
partition "Job with Simple Sequence" {
  group "Straight Line Sequence"
      #green:A(0);
      :B(0);
      :C(0);
      :B(1);
      :C(1);
      #red:D(0);
  end group
}
@enduml
