/'

Tutorial - Simple Sequence Definition
  
'/

@startuml 
partition "Job with Simple Sequence" {
  group "Straight Line Sequence"
      #green:A;
      :B;
      :C;
      :D;
      #red:E;
  end group
}
@enduml
