/'

Tutorial - Inclusive OR Fork Topology
  
'/

@startuml 
partition "Incl OR Fork" {
group "Incl OR Fork"
      #green:A;
      :B;
  split 
      :C;
      :E;
      :F;
      :G;
      :K;
      #red:L;
      detach
  split again
      #red:D;
      detach
  end split
end group
}      
@enduml
