/'

Tutorial - Inclusive OR Fork Topology
  
'/

@startuml 
partition "Incl OR Fork" {
group "Incl OR Fork"
      #green:A;
      :B;
  if (IOR) then ("optional branch name") 
      :C;
      :E;
      :F;
      :G;
      :K;
      #red:L;
      detach
  else ("other optional branch name")
      #red:D;
      detach
  endif
end group
}      
@enduml
