/'

  Tutorial - Constrained Loop

'/

@startuml
partition "Job with Loop Count Definition" {
  group "Sequence with Loop"
    #green:A;
    repeat
      :B;
      :C;
      :D;
    repeat while (LCNT=X)
    floating note
      Name 'LCNT' in the loop
      condition.  PLUS will
      deliver the constraint
      as src event data on an
      event ahead of the loop
      and as user event data on
      an event inside the loop.
    end note
    #red:E;
end group
}
@enduml
