@startuml
partition "Job with Loop and Break" {
  group "Example of Loop with Break"
    #green:A,LCNT,SRC,user=B,name=X>
    note right 
      loop with counter
      and defined user
    end note
    repeat
      :B<
      :C;
      if (XOR) then (error)
        :CError;
        break
      else (normal)
        :D;
      endif
    repeat while
    #red:E;
  end group
}
@enduml
