@startuml
partition "Job with Loop Count Definition" {
  group "Sequence with Loop"
    #green:A,LCNT,SRC,name=X;
    note right 
      Define the loop count
      on the event preceding
      the loop.
    end note
    repeat
      :B,LCNT,USER,name=X;
      note right 
        Mark the user of the
        loop count inside the
        loop, preferrably on
        The first event inside
        the loop.
      end note
      :C;
      :D;
    repeat while
    #red:E;
end group
}
@enduml
