/'

Tutorial - Simple Sequence Definition
  
'/

@startuml 
partition "Job with Simple Sequence" {
  group "Straight Line Sequence"
      #green:A_1;
      :B_1;
      :C_1;
      :B_2;
      :C_2;
      #red:D_1;
  end group
}
@enduml
