/'

Tutorial - Mixed Logic Fork with possible Merge Topology
  
'/

@startuml 
partition "Mixed Logic Fork" {
group "Mixed Logic Fork"
      #green:A;
      :B;
  if (XOR) then ("e.g. normal")
    split
      :C;
    split again  
      :E;
    split again  
      :F;
    end split  
      :G;
  else ("e.g. error")
      #red:D;
      detach
  endif
      :K;
      #red:L;
      detach
end group
}      
@enduml
