/'

Tutorial - Branch and Merge Count Definition
  
'/

@startuml 
partition "Job with Branch and Merge Count Definition" {
  group "Sequence with Branch and Merge"
      #green:A;
      :B,BCNT,name=Y,MCNT,user=D,name=Z;
      note right 
        B will branch by a
        run-time value times.
      end note
      :C;
      :D;
      note right
        D will be the merge point. In this simple
        example the branch count and the merge count 
        should be the same at runtime. In other scenarios
        they could be different.
      end note
      #red:E;
  end group
}
@enduml
