/'

Tutorial - Bank Transfer Example
  
'/

@startuml 
partition "**JobDefinition** Bank Transfer" {
group **SequenceDefinition** Near Side Bank Transfer
      #green:A;
      :B;
      :C;
      :D;
      :E;
      :F;
      :G;
      :H;
  split
      :I;
      :J;
      :K;
      #red:L;
      detach
  split again
      #red:M;
      detach
  end split    
end group
detach
group **SequenceDefinition** Mid Sequence
      #green:N;
      #red:P;
end group
detach
group **SequenceDefinition** Low Catcher Sequence
      #green:Q;
      #red:R;
end group
}      
@enduml