/'

Tutorial - Simple Sequence Definition
  
'/

@startuml 
partition "Job with multiple event occurrences" {
  group "Sequence with split with multiple event occurrences"
      #green:A_1;
      :B_1;
      :C_1;
      split
        :B_2;
        #red:C_2;
        detach
      split again
        #red:D_1;
        detach
      end split
  end group
}
@enduml
