/'

Tutorial - Extra Job Invariant Source Definition
  
'/

@startuml 
      #green:H,1;
      :I,1;
      #red:J,1;
      note right 
        ExtraJobInvariant Name=Q Source=J,1
      end note
      
@enduml