@startuml
partition "Job with Loop and Break" {
  group "Example of Loop with Break"
    #green:A;
    repeat
      :B;
      :C;
      if (XOR) then (error)
        :CError;
        break
      else (normal)
        :D;
      endif
    repeat while (LCNT=X)
    #red:E;
  end group
}
@enduml
