/'

Tutorial - Simple Sequence Definition
  
'/

@startuml 
partition "Job with multiple event occurrences" {
  group "Sequence with split with multiple event occurrences"
      #green:A;
      :B;
      :C;
      split
        :B(1);
        #red:C(1);
        detach
      split again
        #red:D;
        detach
      end split
  end group
}
@enduml
