/'

Tutorial - And Fork Topology
  
'/

@startuml 
partition "AND Fork" {
group "AND Fork"
      #green:A;
      :B;
  split
      :C;
      :E;
      :F;
      :G;
      :K;
      #red:L;
      detach
  split again
      #red:D;
      detach
  end split    
end group
}      
@enduml
