/'

Tutorial - Mixed Logic Fork with possible Merge Topology
  
'/

@startuml 
partition "**JobDefinition** Mixed Logic Fork" {
group **SequenceDefinition** Mixed Logic Fork
      #green:A;
      :B;
  if (XOR) then (e.g. normal)
    split
      :C;
    split again  
      :E;
    split again  
      :F;
    end split  
      :G;
  else (e.g. error)
      #red:D;
      detach
  endif
      :K;
      #red:L;
end group
}      
@enduml