/'

Extra Job Invariant Source Job
  
'/

@startuml (id=EJI1_Source)
title ExtraJobInvariantSource
	:EJIA,1;
	:EJIB,1;
	repeat
      :EJIC,1;
      :EJID,1;
    repeat while (XOR)
    :EJIE,1;
    :EJIG,1;
    note right
    	ExtraJobInvariant Name=EJI1, Source=EJIG,1
    end note

@enduml