@startuml
partition "File Transfer - simple Definition" {
  group "File Transfer - simple"
    #green:RequestFileS;
    :PacketiseFileS;
    :AssemblePacketS;
    :TransferPacketS;
    #red:TransferResultStatusS;
  end group
}  
@enduml
