version: "3.9"
services:
  aereception:
    image: "ghcr.io/xtuml/aereception"
    build:
      context: .
      args:
        EXTRA_MASL_ARGS: "-skiptranslator Sqlite"
#    ports:
#      - "20000:20000"
#      - "30000:30000"
#      - "40000:40000"
    volumes:
      - "./config:/root/config"
      - "../test-files/aer-incoming:/root/incoming"
      - "../test-files/aer-processing:/root/processing"
      - "../test-files/aer-processed:/root/processed"
      - "../test-files/verifier-incoming:/root/outgoing"
    command: "-configPath config/ -preinit schedule/startup.sch -util Inspector -inspector-port 0"
