@startuml

title "BankDeposit (part 1)"
participant Customer
participant Teller
participant System
Customer -> Teller : SendCheck
Customer -> Teller : SendDepositSlip
Teller -> Teller : ScanDocuments
Teller -> Teller : EnterInformation
Teller -> System : SubmitForReview

title "BankDeposit (part 2)"
participant System
participant Auditor
System -> System : VerifyAmount
System -> System : VerifyAccountNumber
System -> Auditor : RequestFraudCheck
Auditor -> System: FraudCheckResponse

participant Teller
participant Customer
Teller -> Customer : GiveReceipt

title BankDeposit
@enduml
