/'

Tutorial - Branch Count Definition
  
'/

@startuml 
partition "Job with Branch Count Definition" {
  group "Sequence with Branch"
      #green:A;
      :B,BCNT,name=Y;
      note right 
        B will branch by a
        run-time value times.
      end note
      :C;
      :D;
      #red:E;
  end group
}
@enduml
