@startuml
partition "Single Complex Job" {
group "Single Sequence"

  #green:SCJA1,LCNT,user=SCJS,name=LC3;
  :SCJA2,BCNT,user=SCJK,name=BC2;
  :SCJB1,LCNT,user=SCJE,name=LC1;
  :SCJB2,LCNT,user=SCJD,name=LC2;
  :SCJB3,IINV,name=InvariantA;
  :SCJC;
  if (XOR) then ("error")
    #red:SCJR;
    detach
  else ("normal")
    fork
      repeat
        :SCJD;
        :SCJE;
        :SCJF;
      repeat while
      :SCJG;
      repeat
        :SCJD;
        :SCJE;
        if (XOR) then ("error")
          :SCJT;
          break
        else ("normal")
          :SCJF;
        endif
      repeat while
    fork again
      :SCJK;
      :SCJL;
      :SCJM;
      if (XOR) then ("error")
        #red:SCJN;
        detach
      endif    
    fork again
      :SCJP;
      #red:SCJQ;
      detach
    fork again
      :SCJC;
      repeat
        :SCJD;
        :SCJE;
      repeat while
      :SCJF,BCNT,name=BC1;
      :SCJD;
      #red:SCJG;
      detach
    fork again
      repeat
        :SCJS;
      repeat while
      :SCJD;
      #red:SCJE;
      detach
    end fork
    :SCJH,IINV,USER,name=InvariantA;
    #red:SCJJ;
    detach
  endif
end group
}
@enduml
@startuml
package "Error Events" {
("error 1")
("error 2")
("error 2")
("error 3")
("error 4")
("error 5")
("error 6")
}
@enduml
