@startuml
partition "AND_constraint_1" {
    group "AND_constraint_1"
        :A;
        :B;
        :C;
        :D;
        :E;
        :F;
        :G;
        :H;
        :I;
        :J;
        :K;
        :L;
        :M;
        :N;
        :O;
        :P;
        :Q;
        :R;
        :S;
        :T;
        :U;
        :V;
        :W;
        :X;
        :Y;
        :Z;
        :AA;
        :AB;
        :AC;
        :AD;
        :AE;
        fork
            :AF;
            detach
        fork again
            :AG;
            detach
        end fork
    end group 
}
@enduml