@startuml 
partition "Simple Job" {
  group "Fund Transfer"
    :requestFunds;
    :requestApproved;
    :fundsTransferred;
    detach
  end group

  package “Unhappy Path Events" {
    :unhappy-path-event-1;
    kill
    :unhappy-path-event-2;
    kill
    :unhappy-path-event-3;
    kill
    :unhappy-path-event-4;
    kill
    :unhappy-path-event-5;
    kill
    :unhappy-path-event-6;
    kill
  }

}
@enduml
