
@startuml 
partition "Branch And Merge Count Job 2" {
  group "Branch and Merge Count Sequence 2"
      #green:BMCJ2A;
      :BMCJ2B,BCNT,user=BMCJ2D,name=BMCJ2BC1,MCNT,user=BMCJ2G,name=BMCJ2MC1;
      :BMCJ2C;
      :BMCJ2D;
      :BMCJ2E;
      :BMCJ2F;
      :BMCJ2G;
      #red:BMCJ2H;
  end group
}
@enduml