
@startuml 
partition "Branch Count Job 1" {
  group "Branch Count Sequence 1"
      #green:BCJ1A;
      :BCJ1B,BCNT,user=BCJ1C,name=BCJ1BC1;
      :BCJ1C;
      :BCJ1D;
      :BCJ1E;
      #red:BCJ1F;
  end group
}
@enduml
