
@startuml 
partition "Branch And Merge Count Job 1" {
  group "Branch and Merge Count Sequence 1"
      #green:BMCJ1A;
      :BMCJ1B,BCNT,user=BMCJ1D,name=BMCJ1BC1;
      :BMCJ1C,MCNT,user=BMCJ1G,name=BMCJ1MC1;
      :BMCJ1D;
      :BMCJ1E;
      :BMCJ1F;
      :BMCJ1G;
      #red:BMCJ1H;
  end group
}
@enduml
