@startuml

partition "Complex No Event Data Job" {

group "Single Complex Sequence"
  #green:A;
  :B;
  :C;
  :D;
  :E;
  :F;
  if (XOR) then ("normal")
    :G;
    fork
      :H;
      :I;
      :J;
    fork again
      :K;
      #red:L;
      detach
    fork again
      :M;
      :N;
      :O;
      :P;
    end fork
    :Q;
    #red:R;
    detach
  else ("error")
    #red:S;
    detach
  endif
end group
}
@enduml
