@startuml

partition "Kitchen Sink Job 2" {
 :EINV,SRC,jobdefn="AA Extra Job Invariant Source Job",
 name=AUTH_TOKEN_A|
 detach
group "Kitchen Sink Sequence 2"

  #green:KSJA,LCNT,user=KSJS,name=LC3,BCNT,user=KSJK,name=BC2,MCNT,user=KSJW,name=MC2;
  :KSJB,LCNT,user=KSJF(0),name=LC1,LCNT,user=KSJD(1),name=LC2,IINV,name=KSJInvB;
  :KSJC;
    :KSJD;
    fork
      :KSJE;
      repeat
        :KSJF;
        :KSJG,EINV,USER,name=AUTH_TOKEN_A;
        :KSJH;
      repeat while
      :KSJI;
      repeat
        :KSJD;
        :KSJE;
        if (XOR) then ("error")
          :KSJT;
          break
        else ("normal")
          :KSJF;
        endif
      repeat while
      :KSJU;
    fork again
      :KSJK;
      :KSJL,EINV,USER,name=AUTH_TOKEN_A;
      :KSJM;
      if (XOR) then ("error")
        #red:KSJN;
        detach
      else ("normal")
        :KSJV;  
      endif
      :KSJW;    
    fork again
      :KSJP;
      #red:KSJQ;
      detach
    fork again
      :KSJC;
      repeat
        :KSJD;
        :KSJE;
      repeat while
      :KSJF,BCNT,name=BC1;
      :KSJD,EINV,USER,name=AUTH_TOKEN_A;
      #red:KSJG;
      detach
    fork again
      :KSJJ;
      repeat
        :KSJS;
      repeat while
      :KSJD;
      #red:KSJE;
      detach
    end fork
    :KSJH,IINV,USER,name=KSJInvB;
    #red:KSJZ;
    detach
end group
}
@enduml