@startuml

partition "Kitchen Sink Job 2" {
 :EINV,SRC,jobdefn="AA Extra Job Invariant Source Job",
 name=AUTH_TOKEN_A|
 detach
group "Kitchen Sink Sequence 2"

  #green:KSJA,LCNT,user=KSJ2S,name=LC3,BCNT,user=KSJ2K,name=BC2,MCNT,user=KSJ2W,name=MC2;
  :KSJB,LCNT,user=KSJ2F(0),name=LC1,LCNT,user=KSJ2D(1),name=LC2,IINV,name=KSJInvB;
  :KSJ2C;
    :KSJ2D;
    fork
      :KSJE;
      repeat
        :KSJF;
        :KSJG,EINV,USER,name=AUTH_TOKEN_A;
        :KSJH;
      repeat while
      :KSJ2I;
      repeat
        :KSJ2D;
        :KSJ2E;
        if (XOR) then ("error")
          :KSJ2T;
          break
        else ("normal")
          :KSJ2F;
        endif
      repeat while
      :KSJ2U;
    fork again
      :KSJ2K;
      :KSJ2L,EINV,USER,name=AUTH_TOKEN_A;
      :KSJ2M;
      if (XOR) then ("normal")
        :KSJ2V;  
      else ("error")
        #red:KSJ2N;
        detach
      endif
      :KSJ2W;    
    fork again
      :KSJ2P;
      #red:KSJ2Q;
      detach
    fork again
      :KSJ2C;
      repeat
        :KSJ2D;
        :KSJ2E;
      repeat while
      :KSJ2F,BCNT,name=BC1;
      :KSJ2D,EINV,USER,name=AUTH_TOKEN_A;
      #red:KSJ2G;
      detach
    fork again
      :KSJ2J;
      repeat
        :KSJ2S;
      repeat while
      :KSJ2D;
      #red:KSJ2E;
      detach
    end fork
    :KSJ2H,IINV,USER,name=KSJInvB;
    #red:KSJ2Z;
    detach
end group
}
@enduml