@startuml
partition "xor_single_events" {
    group "sor_single_events"
        switch ("XOR")
            case ("1")
                :XSE1;
            case ("2")
                :XSE2;
            case ("3")
                :XSE3;
        endswitch
    end group
}
@enduml
