/'

Welcome and thank you for using Pladitor!
=========================================

First Steps Overview
--------------------

The Sidebar Menu provides these functionalities:
    ------------

 - Editor:       This page. Work on your diagrams here.
 - Templates:    The template gallery for all kinds of 
                 diagram types
 - Preferences:  Settings page to set language, theme etc.
 - Feedback:     A page for giving feedback to the  
                 Pladitor team.
 - About:        General information about Pladitor.
 
The Top Toolbar provides these functionalities:
    -----------
    
  - Open diagram from text-, PNG-, or SVG-files
  - Add diagram to custom templates gallery
  - Show keyboard shortcuts
  - Open external help URL
  - Save diagram source as text file
  - Export diagram as SVG, PNG, EPS, TXT, or URL
  
'/

@startuml (id=Branch_1)
title TopBranch
    repeat
      :XD,1;
      :XE,1;
      :XF,1;
    repeat while (XOR)
    :XG,1;
    repeat
      :XD,2;
      :XE,2;
      if (XOR) then (error)
        :XT,1;
        break
      else (normal)
        :XF,2;
      endif
    repeat while (XOR)

@enduml