global:
  config_version: 3
input:
  type: file
  paths: 
    - /var/log/reception/Reception.log
    - /var/log/verifier/Verifier.log
  #readall: true
  fail_on_missing_logfile: false
imports:
- type: grok_patterns
  dir: ./logstash-patterns-core/patterns
metrics:
# Reception metrics
- type: counter
  name: reception_file_processed
  help: Number of files processed by the AEReception domain.
  match: '%{NUMBER:pv_index} reception_file_processed'
  path: /var/log/reception/Reception.log
  labels:
    pv_index: '{{.pv_index}}'
- type: counter
  name: reception_file_validated
  help: Number of files validated against the JSON schema by the AEReception domain.
  match: '%{NUMBER:pv_index} reception_file_validated'
  path: /var/log/reception/Reception.log
  labels:
    pv_index: '{{.pv_index}}'
- type: counter
  name: reception_event_added
  help: Number of events added by the AEReception domain.
  match: '%{NUMBER:pv_index} reception_event_added : JobId = %{UUID:job_id} : EventId = %{UUID:event_id} : EventType = %{WORD:event_type}'
  path: /var/log/reception/Reception.log
  labels:
    pv_index: '{{.pv_index}}'
    job_id: '{{.job_id}}'
    event_id: '{{.event_id}}'
    event_type: '{{.event_type}}'
- type: counter
  name: reception_file_process_error
  help: Number of failures processing the incoming file by the AEReception domain.
  match: '%{NUMBER:pv_index} reception_file_process_error : FailureReason = %{WORD:failure_reason}'
  path: /var/log/reception/Reception.log
  labels:
    pv_index: '{{.pv_index}}'
    failure_reason: '{{.failure_reason}}'
# Verifier metrics
- type: counter
  name: aeordering_job_processed
  help: Number of jobs processed by the AEOrdering domain.
  match: '%{NUMBER:pv_index} aeordering_job_processed : JobId = %{UUID:job_id}'
  path: /var/log/verifier/Verifier.log
  labels:
    pv_index: '{{.pv_index}}'
    job_id: '{{.job_id}}'
- type: counter
  name: aeordering_events_processed
  help: Number of events processed by the AEOrdering domain.
  match: '%{NUMBER:pv_index} aeordering_events_processed : JobId = %{UUID:job_id} : EventId = %{UUID:event_id} : EventType = %{WORD:event_type}'
  path: /var/log/verifier/Verifier.log
  labels:
    pv_index: '{{.pv_index}}'
    job_id: '{{.job_id}}'
    event_id: '{{.event_id}}'
    event_type: '{{.event_type}}'
- type: counter
  name: aeordering_events_blocked
  help: Number of events blocked by the AEOrdering domain.
  match: '%{NUMBER:pv_index} aeordering_events_blocked : JobId = %{UUID:job_id} : EventId = %{UUID:event_id} : EventType = %{WORD:event_type}'
  path: /var/log/verifier/Verifier.log
  labels:
    pv_index: '{{.pv_index}}'
    job_id: '{{.job_id}}'
    event_id: '{{.event_id}}'
    event_type: '{{.event_type}}'
- type: counter
  name: aeordering_events_failed
  help: Number of events blocked by the AEOrdering domain.
  match: '%{NUMBER:pv_index} aeordering_events_failed : JobId = %{UUID:job_id} : EventId = %{UUID:event_id} : EventType = %{WORD:event_type} : FailureReason = %{WORD:failure_reason}'
  path: /var/log/verifier/Verifier.log
  labels:
    pv_index: '{{.pv_index}}'
    job_id: '{{.job_id}}'
    event_id: '{{.event_id}}'
    event_type: '{{.event_type}}'
    failure_reason: '{{.failure_reason}}'
- type: counter
  name: aeordering_duplicate_job
  help: Number of duplicate jobs identified by the AEOrdering domain.
  match: '%{NUMBER:pv_index} aeordering_duplicate_job : JobId = %{UUID:job_id} : EventId = %{UUID:event_id} : EventType = %{WORD:event_type} : FailureReason = %{WORD:failure_reason}'
  path: /var/log/verifier/Verifier.log
  labels:
    pv_index: '{{.pv_index}}'
    job_id: '{{.job_id}}'
    event_id: '{{.event_id}}'
    event_type: '{{.event_type}}'
    failure_reason: '{{.failure_reason}}'
- type: counter
  name: aeordering_file_processing_failure
  help: Number of failures processing incoming file by the AEOrdering domain.
  match: '%{NUMBER:pv_index} aeordering_file_processing_failure : File = %{WORD:filename} : FailureReason = %{WORD:failure_reason}'
  path: /var/log/verifier/Verifier.log
  labels:
    pv_index: '{{.pv_index}}'
    filename: '{{.filename}}'
    failure_reason: '{{.failure_reason}}'
- type: counter
  name: aeordering_job_failed
  help: Number of job failures by the AEOrdering domain.
  match: '%{NUMBER:pv_index} aeordering_job_failed : JobId = %{UUID:job_id} : FailureReason = %{WORD:failure_reason}'
  path: /var/log/verifier/Verifier.log
  labels:
    pv_index: '{{.pv_index}}'
    job_id: '{{.job_id}}'
    failure_reason: '{{.failure_reason}}'
- type: counter
  name: svdc_new_job_started
  help: Number of job starting in the SVDC domain.
  match: '%{NUMBER:pv_index} svdc_new_job_started : JobId = %{UUID:job_id} : EventId = %{UUID:event_id} : EventType = %{WORD:event_type}'
  path: /var/log/verifier/Verifier.log
  labels:
    pv_index: '{{.pv_index}}'
    job_id: '{{.job_id}}'
    event_id: '{{.event_id}}'
    event_type: '{{.event_type}}'
- type: counter
  name: svdc_job_failed
  help: Number of job failures detected by the SVDC domain.
  match: '%{NUMBER:pv_index} svdc_job_failed : JobId = %{UUID:job_id} : FailureReason = %{WORD:failure_reason}'
  path: /var/log/verifier/Verifier.log
  labels:
    pv_index: '{{.pv_index}}'
    job_id: '{{.job_id}}'
    failure_reason: '{{.failure_reason}}'
- type: counter
  name: svdc_job_definition_failed
  help: Number of job definition failures detected by the SVDC domain.
  match: '%{NUMBER:pv_index} svdc_job_definition_failed : FailureReason = %{WORD:failure_reason}'
  path: /var/log/verifier/Verifier.log
  labels:
    pv_index: '{{.pv_index}}'
    failure_reason: '{{.failure_reason}}'
- type: counter
  name: svdc_job_success
  help: Number of successful jobs completed by the SVDC domain.
  match: '%{NUMBER:pv_index} svdc_job_success : JobId = %{UUID:job_id} : JobName = %{WORD:job_name}'
  path: /var/log/verifier/Verifier.log
  labels:
    pv_index: '{{.pv_index}}'
    job_id: '{{.job_id}}'
    job_name: '{{.job_name}}'
- type: counter
  name: svdc_invalid_event
  help: Number of invalid events reported by the SCDC domain.
  match: '%{NUMBER:pv_index} svdc_invalid_event : JobId = %{UUID:job_id} : EventId = %{UUID:event_id} : EventType = %{WORD:event_type} : FailureReason = %{WORD:failure_reason}'
  path: /var/log/verifier/Verifier.log
  labels:
    pv_index: '{{.pv_index}}'
    job_id: '{{.job_id}}'
    event_id: '{{.event_id}}'
    event_type: '{{.event_type}}'
    failure_reason: '{{.failure_reason}}'
- type: counter
  name: svdc_invalid_event_definition
  help: Number of event definition failures detected by the SVDC domain.
  match: '%{NUMBER:pv_index} svdc_invalid_event_definition : FailureReason = %{WORD:failure_reason}'
  path: /var/log/verifier/Verifier.log
  labels:
    pv_index: '{{.pv_index}}'
    failure_reason: '{{.failure_reason}}'
server:
  port: 9144
