
@startuml 
partition "Branch Count Job 2" {
  group "Branch Count Sequence 2"
      #green:BCJ2A;
      :BCJ2B,BCNT,user=BCJ2B,name=BCJ2BC2;
      :BCJ2C;
      :BCJ2D;
      :BCJ2E;
      #red:BCJ2F;
  end group
}
@enduml
