@startuml
partition "Loop Count Job" {
group "Loop Count Sequence"
  #green:LCJAa;
  :LCJAb;
  :LCJBa,LCNT,user=LCJE(0),name=LC1;
  :LCJBb;
  :LCJBc;
  :LCJC;
  if (XOR) then ("normal")
    :SJCDa;
    fork
      :LCJC;
      repeat
        :LCJDc;
        :LCJE;
      repeat while
      :LCJF;
      :LCJD;
      :LCJG;
    fork again
    :SJCDb;
      :LCJG;
      :SJCFa;
    fork again
      :LCJP;
      #red:LCJQ;
    end fork
    :LCJH;
    #red:LCJJ;
    detach
  else ("error")
    #red:LCJR;
    detach
  endif
end group
}
@enduml