/'

PLUS User Guide - Simple Sequence Definition
  
'/

@startuml 
partition "BankDeposit" {
  group "BankDeposit"
      :SendCheck;
      :SendDepositSlip;
      :ScanDocuments;
      :EnterInformation;
      :SubmitForReview;
  end group
}
@enduml
