/'

PLUS User Guide - Simple Sequence Definition
  
'/

@startuml 
partition "Simple Job" {
  group "Fund Transfer"
    :requestFunds;
    :requestApproved;
    :fundsTransferred;
  end group
}
@enduml
