@startuml
partition "File Transfer with XOR Definition" {
  group "File Transfer with XOR"
    #green:RequestFileX;
    :PacketiseFileX;
    if (XOR) then (normal)
      :AssemblePacketX;
    else (alternative)
      #red:ReportInvalidFileX;
      detach
    endif
    :TransferPacketX;
    #red:TransferResultStatusX;
  end group
}  
@enduml
