name: Build and Publish
on:
  release:
    types: [published]

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    env:
      ARTIFACTORY_USERNAME: build_server
      ARTIFACTORY_TOKEN: ${{ secrets.ARTIFACTORY_TOKEN }}
    steps:
      - uses: actions/checkout@v3

      - name: Create Conan Cache
        run: docker volume create conan-cache

      - name: Cache Artifacts
        id: cache-primes
        uses: actions/cache@v3
        with:
          path: /var/lib/docker/volumes/conan-cache
          key: $(docker compose -f bin/docker-compose.yml run --rm bash conan profile show)

      - name: Generate MASL
        run: |
          cd models/
          ./gen_all.sh

      - name: Build and Publish
        env:
          MUNIN_VERSION: ${{ github.ref_name }}
        run: |
          cd models/
          ./publish_all.sh

      - name: Create Production Staging Area
        env:
          MUNIN_VERSION: ${{ github.ref_name }}
        run: |
          cd prod/pv_proc/
          ../stage-project.sh

      - uses: docker/setup-buildx-action@v2

      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate docker metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/xtuml/protocol_verifier

      - name: Build/push image
        uses: docker/build-push-action@v3
        with:
          context: prod/pv_proc
          tags: ${{ steps.meta.outputs.tags }}
          push: true
