version: "3.9"
services:
  aeordering_test:
    image: "ghcr.io/xtuml/aeordering:test"
    build:
      context: .
      target: install-test
      args:
        EXTRA_MASL_ARGS: "-skiptranslator Sqlite"
    ports:
      - "20000:20000"
      - "30000:30000"
      - "40000:40000"
    volumes:
      - "./test_results:/root/test_results"
      - "./config:/root/config"
      - "./test-files:/root/test-files"
    entrypoint: ["/usr/bin/timeout", "3000s", "AEOrdering_transient_standalone"]
    command: "-log-level Debug -configPath config/ -configFile aeordering_spec_test.json -postinit schedule/test.sch -startJobGroup 00 -endJobGroup FF -util Inspector -inspector-port 0"
